(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),W=1120,H=720,TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)];
const safeLoad=()=>{try{return JSON.parse(localStorage.getItem('ember-records')||'{}')}catch{return{}}};let records=safeLoad();
let mode='title',floor=1,rooms=[],room,p,shots=[],particles=[],bombs=[],time=0,kills=0,clears=0,shake=0,transition=0,last=0,toastTime=0,seed=0,elapsed=0;
const keys=new Set(),mouse={x:560,y:350,down:false,active:false},move={x:0,y:0},aim={x:0,y:0};const coarse=matchMedia('(pointer:coarse)').matches;
const dirs=[{x:0,y:-1,op:2},{x:1,y:0,op:3},{x:0,y:1,op:0},{x:-1,y:0,op:1}];
const floorNames=['Затонувшая часовня','Сад заблудших','Сердце пустоты'],bossNames=['Звонарь без лица','Королева терний','Пожиратель огня'];
const relics=[
{id:'ember',icon:'✦',name:'Угольная звезда',desc:'Урон +35%. Каждый выстрел становится опаснее.',rarity:'СИЛА',apply:()=>p.damage*=1.35},
{id:'double',icon:'⋈',name:'Зеркальная слеза',desc:'Два снаряда вместо одного. Урон каждого −20%.',rarity:'МУТАЦИЯ',apply:()=>{p.multishot++;p.damage*=.8}},
{id:'fast',icon:'ϟ',name:'Пульс шторма',desc:'Стрельба на 28% быстрее.',rarity:'СКОРОСТЬ',apply:()=>p.rate*=.72},
{id:'pierce',icon:'⟡',name:'Игла рассвета',desc:'Снаряды проходят сквозь врагов.',rarity:'МУТАЦИЯ',apply:()=>p.pierce=true},
{id:'homing',icon:'☽',name:'Лунный глаз',desc:'Снаряды плавно наводятся на ближайшего врага.',rarity:'МУТАЦИЯ',apply:()=>p.homing=true},
{id:'burn',icon:'♨',name:'Живой пепел',desc:'Попадания поджигают врагов на 3 секунды.',rarity:'СИНЕРГИЯ',apply:()=>p.burn=true},
{id:'frost',icon:'❄',name:'Зимний обет',desc:'Попадания замедляют врагов на 45%.',rarity:'КОНТРОЛЬ',apply:()=>p.frost=true},
{id:'heart',icon:'♥',name:'Второе сердце',desc:'+2 к максимальному здоровью. Лечит 3 раны.',rarity:'ЖИЗНЬ',apply:()=>{p.maxHp+=2;p.hp=Math.min(p.maxHp,p.hp+3)}},
{id:'speed',icon:'➶',name:'Перо странника',desc:'Движение +20%. Рывок восстанавливается быстрее.',rarity:'ЛОВКОСТЬ',apply:()=>{p.speed*=1.2;p.dashMax*=.75}},
{id:'orbit',icon:'◎',name:'Маленькое солнце',desc:'Спутник кружит вокруг тебя и обжигает врагов.',rarity:'СПУТНИК',apply:()=>p.orbits++},
{id:'ricochet',icon:'◇',name:'Осколок зеркала',desc:'Снаряды один раз отскакивают от стен.',rarity:'МУТАЦИЯ',apply:()=>p.bounce=true},
{id:'vampire',icon:'†',name:'Алый договор',desc:'Каждое восьмое убийство восстанавливает 1 здоровье.',rarity:'ЖИЗНЬ',apply:()=>p.vampire=true},
{id:'blast',icon:'✹',name:'Карманная комета',desc:'+4 бомбы. Взрывы наносят вдвое больше урона.',rarity:'РАЗРУШЕНИЕ',apply:()=>{p.bombs+=4;p.bombDamage*=2}},
{id:'shield',icon:'⬡',name:'Тихий страж',desc:'Первый удар в каждой комнате поглощается щитом.',rarity:'ЗАЩИТА',apply:()=>{p.shieldRelic=true;p.shield=true}},
{id:'heavy',icon:'✧',name:'Сердце метеора',desc:'Крупные снаряды. Урон +60%, стрельба −15%.',rarity:'СИЛА',apply:()=>{p.damage*=1.6;p.size+=2;p.rate*=1.15}},
{id:'nova',icon:'❋',name:'Последний свет',desc:'При получении урона выпускает кольцо огня.',rarity:'СИНЕРГИЯ',apply:()=>p.nova=true},
{id:'heal',icon:'✚',name:'Глоток рассвета',desc:'Восстанавливает всё здоровье и даёт 15 монет.',rarity:'ПОДДЕРЖКА',apply:()=>{p.hp=p.maxHp;p.coins+=15}}
];
function sfx(name,x=560){window.EmberAudio?.play(name,x)}
const startVoice=new Audio("https://dnznrvs05pmza.cloudfront.net/text_to_speech/86be1410-6139-4d51-ad3e-ca5ab9cc5ee2/_________________________.mp3?_jwt=eyJhbGciOiJIUzI1NiIsImtleUhhc2giOiJlZmJlMDM4ZmY1MWFhMWMxIiwiYnVja2V0IjoicnVud2F5LXRhc2stYXJ0aWZhY3RzIiwic3RhZ2UiOiJwcm9kIiwiZXhwIjoxNzkxNTMyMTc1fQ.Cjn8gu33aXjFzimhbIUXHoWok5aQHK3Hr-ky2c9cy2c");startVoice.preload='auto';startVoice.volume=.82;function playStartVoice(){try{startVoice.currentTime=0;startVoice.play().catch(()=>{})}catch{}}document.addEventListener('click',e=>{if(e.target&&e.target.id==='start')playStartVoice()});

function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;toastTime=3}
function burst(x,y,color,n=12,speed=100){for(let i=0;i<n;i++){let a=rnd(0,TAU),v=rnd(speed*.2,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.25,.65),max:.65,r:rnd(1.5,4),color})}if(particles.length>350)particles.splice(0,particles.length-350)}
function makeRoom(x,y,type='fight'){return{x,y,type,seen:false,clear:false,enemies:[],rocks:[],pickups:[],doors:[],decor:Array.from({length:55},()=>({x:rnd(100,1020),y:rnd(155,615),r:rnd(1,4),a:rnd(0,TAU)})),reward:false}}
function generate(){rooms=[makeRoom(0,0,'start')];const count=9+floor*2;while(rooms.length<count){const base=pick(rooms),d=pick(dirs),x=base.x+d.x,y=base.y+d.y;if(!rooms.some(r=>r.x===x&&r.y===y)&&Math.abs(x)<4&&Math.abs(y)<4)rooms.push(makeRoom(x,y))}const sorted=rooms.slice(1).sort((a,b)=>(Math.abs(b.x)+Math.abs(b.y))-(Math.abs(a.x)+Math.abs(a.y)));sorted[0].type='boss';pick(sorted.slice(1,Math.ceil(sorted.length/2)+1)).type='treasure';pick(sorted.filter(r=>r.type==='fight')).type='shop';for(const r of rooms){r.doors=dirs.map(d=>rooms.find(q=>q.x===r.x+d.x&&q.y===r.y+d.y));if(r.type==='fight'){for(let j=0;j<2+floor+Math.floor(rnd(0,3));j++){let e=enemy(pick(['wisp','crawler','eye','brute','splitter'].slice(0,Math.min(5,3+floor))),rnd(260,860),rnd(240,500));r.enemies.push(e)}const layouts=[[[320,275],[800,445]],[[320,275],[800,275],[320,445],[800,445]],[[450,350],[670,350]],[[340,360],[780,360]],[]];r.rocks=pick(layouts).map(([x,y])=>({x,y,r:25,hp:50}));for(const e of r.enemies)for(const rock of r.rocks)if(dist(e,rock)<65)e.y+=90}else if(r.type==='boss')r.enemies=[enemy('boss',560,280)];else r.clear=true;if(r.type==='shop')r.pickups=[{x:440,y:370,type:'heal',price:12},{x:560,y:370,type:'relic',price:25},{x:680,y:370,type:'bomb',price:8}]}enter(rooms[0]);}
function enemy(type,x,y){const hp={wisp:15,crawler:22,eye:25,brute:55,splitter:32,baby:9,boss:220+floor*110}[type]*(1+(floor-1)*.2);return{x,y,type,hp,maxHp:hp,r:type==='boss'?40:type==='brute'?24:type==='baby'?11:18,t:rnd(0,3),cool:rnd(.8,2),hit:0,burn:0,slow:0,phase:0,charge:0,vx:0,vy:0,orbitHit:0}}
function enter(r,dir=-1){if(dir>=0)sfx('door');room=r;r.seen=true;shots=[];bombs=[];particles=[];transition=.45;p.x=dir===1?135:dir===3?985:560;p.y=dir===0?570:dir===2?185:420;p.inv=1;p.shield=!!p.shieldRelic;if(r.type==='start'&&floor===1)toast('Зачисти комнаты. Ищи реликвии. Дойди до босса.');if(r.type==='treasure'&&!r.reward){r.reward=true;choose('Сокровище ждало тебя')}if(r.type==='shop')toast('Коснись предмета, чтобы купить его');if(r.type==='boss'&&!r.clear){toast(bossNames[floor-1]);sfx('entrance')}hud();}
function start(){window.EmberAudio?.unlock();floor=1;elapsed=0;kills=0;clears=0;seed=Math.floor(Math.random()*999999);p={x:560,y:420,r:14,hp:8,maxHp:8,speed:205,damage:12,rate:.28,shot:0,size:5,multishot:1,inv:0,dash:0,dashCd:0,dashMax:1.25,dx:0,dy:1,coins:0,bombs:3,bombDamage:85,relics:[],orbits:0,walk:0,animSpeed:0,facing:{x:0,y:1},aimAngle:Math.PI/2,recoil:0,hurtAnim:0,trail:[]};mode='play';$('overlay').className='overlay hidden';$('hud').classList.remove('hidden');$('touchControls').classList.toggle('hidden',!coarse);generate();canvas.focus();sfx('start');}
function hud(){if(!p)return;$('hearts').innerHTML='♥'.repeat(Math.ceil(p.hp/2))+'<span class="empty">'+'♡'.repeat(Math.max(0,Math.ceil(p.maxHp/2)-Math.ceil(p.hp/2)))+'</span>';$('hearts').innerHTML+=' <small style="font:11px Manrope,sans-serif;letter-spacing:0">'+Math.ceil(p.hp)+'/'+p.maxHp+'</small>';$('hearts').title=`Здоровье: ${Math.ceil(p.hp)} / ${p.maxHp}`;$('coins').textContent='◈ '+p.coins;$('bombs').textContent='✹ '+p.bombs;$('floorLabel').textContent=`ГЛУБИНА ${floor} / 3`;$('roomLabel').textContent=floorNames[floor-1];$('relicCount').textContent='✧ '+p.relics.length+' реликвий';$('timer').textContent=`${Math.floor(elapsed/60).toString().padStart(2,'0')}:${Math.floor(elapsed%60).toString().padStart(2,'0')}`;const boss=room.enemies.find(e=>e.type==='boss'&&e.hp>0);$('bossBar').classList.toggle('hidden',!boss);if(boss){$('bossName').textContent=bossNames[floor-1];$('bossHealth').style.width=(boss.hp/boss.maxHp*100)+'%'}}
function panel(html){$('overlay').className='overlay clear';$('overlay').innerHTML='<div class="panel">'+html+'</div>';mouse.down=false;keys.clear();move.x=move.y=aim.x=aim.y=0;}
function choose(title){mode='choice';let pool=relics.filter(r=>!p.relics.includes(r.id)||['ember','heart','fast','speed','orbit','heal','blast','heavy'].includes(r.id));let options=[];while(options.length<3){let r=pick(pool);options.push(r);pool=pool.filter(q=>q!==r)}panel(`<div class="kicker">ДАР ПОДЗЕМЕЛЬЯ</div><h2>${title}</h2><p>Выбери одну реликвию. Её сила останется до конца забега.</p><div class="choices">${options.map((r,i)=>`<button class="choice" data-choice="${i}"><span class="icon">${r.icon}</span><strong>${r.name}</strong><small>${r.desc}</small><i>${r.rarity}</i></button>`).join('')}</div>`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const r=options[+b.dataset.choice];r.apply();p.relics.push(r.id);mode='play';$('overlay').classList.add('hidden');toast(r.name+' — '+r.desc);sfx('relic');hud()});}
function end(win){mode=win?'win':'dead';records.runs=(records.runs||0)+1;records.best=Math.max(records.best||0,kills);if(win)records.wins=(records.wins||0)+1;try{localStorage.setItem('ember-records',JSON.stringify(records))}catch{}panel(`<div class="kicker">${win?'ТЬМА ОТСТУПИЛА':'ОГОНЬ ЕЩЁ ПОМНИТ ТЕБЯ'}</div><h2>${win?'Сердце снова бьётся.':'Даже пепел может вспыхнуть.'}</h2><p>${win?'Ты вернул свет в затонувшую часовню. Но подземелье уже меняется — следующий путь будет другим.':'Этот путь закончился. Следующий принесёт новые комнаты, реликвии и сочетания сил.'}</p><p>Глубина ${floor} / 3 · ${kills} врагов · ${p.relics.length} реликвий · ${Math.floor(elapsed/60)} мин ${Math.floor(elapsed%60)} сек</p><button class="primary" id="again">ЕЩЁ ОДИН ОГОНЬ ↗</button> <a class="secondary" href="/">На сайт</a>`);$('again').onclick=start;sfx(win?'win':'dead');}
function pause(){if(!['play','pause'].includes(mode))return;if(mode==='pause'){mode='play';$('overlay').classList.add('hidden');last=performance.now();return}mode='pause';panel(`<div class="kicker">ОГОНЬ НЕ ПОГАСНЕТ</div><h2>Переведи дыхание.</h2><p>WASD — движение. Зажми мышь или стрелки — стрельба.<br>Пробел — неуязвимый рывок. E — бомба.<br>Двери открываются после зачистки. Мини-карта справа внизу.<br>На телефоне: два стика и кнопки рывка и бомбы.</p><p>${p.relics.length?p.relics.map(id=>relics.find(r=>r.id===id)?.name).join(' · '):'Реликвий пока нет'}</p><button id="resume" class="primary">ПРОДОЛЖИТЬ</button>`);$('resume').onclick=pause;}
function hurt(n){if(p.inv>0||p.dash>0||mode!=='play')return;if(p.shield){p.shield=false;p.inv=.6;burst(p.x,p.y,'#b9e8dc',25);sfx('shield');return}p.hp=Math.max(0,p.hp-n);p.hurtAnim=1;p.inv=1.1;shake=8;burst(p.x,p.y,'#e58c75',18);sfx('hurt');if(p.nova)for(let i=0;i<12;i++)shoot(p.x,p.y,i*TAU/12,true);if(p.hp<=0)end(false);hud();}
function damage(e,n){if(e.hp<=0)return;if(n>=1)sfx('hit',e.x);e.hp-=n;e.hit=.12;if(e.hp<=0){kills++;burst(e.x,e.y,e.type==='boss'?'#f3bb72':'#8da59a',e.type==='boss'?65:16,150);sfx('kill',e.x);room.pickups.push({x:e.x,y:e.y,type:'coin'});if(Math.random()<.09)room.pickups.push({x:e.x+18,y:e.y,type:'heal'});if(e.type==='splitter')for(let i=0;i<2;i++)room.enemies.push(enemy('baby',e.x+rnd(-15,15),e.y+rnd(-15,15)));if(p.vampire&&kills%8===0)p.hp=Math.min(p.maxHp,p.hp+1);hud()}}
function shoot(x,y,a,friendly=true,speed=480){if(friendly){p.recoil=1;p.aimAngle=a;p.facing={x:Math.cos(a),y:Math.sin(a)}}shots.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:friendly?p.size:6,life:friendly?1.8:5,friendly,damage:p.damage,bounce:friendly&&p.bounce?1:0,hit:new Set()})}
function dash(){if(mode!=='play'||p.dashCd>0)return;let x=move.x||((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)),y=move.y||((keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));if(Math.hypot(x,y)<.1){x=p.dx;y=p.dy}const n=Math.hypot(x,y)||1;p.dx=x/n;p.dy=y/n;p.dash=.17;p.dashCd=p.dashMax;sfx('dash',p.x);}
function bomb(){if(mode!=='play'||!p.bombs)return;p.bombs--;bombs.push({x:p.x,y:p.y,t:1.1});hud();sfx('bomb',p.x)}
function moveBody(o,dx,dy,rocks=true){o.x=clamp(o.x+dx,94+o.r,1026-o.r);o.y=clamp(o.y+dy,151+o.r,620-o.r);if(rocks)for(const r of room.rocks){const d=dist(o,r),min=o.r+r.r;if(d<min){const a=Math.atan2(o.y-r.y,o.x-r.x);o.x=r.x+Math.cos(a)*min;o.y=r.y+Math.sin(a)*min}}}
function update(dt){time+=dt;toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;for(const f of particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.97;f.vy*=.97}particles=particles.filter(f=>f.life>0);shake=Math.max(0,shake-dt*30);transition=Math.max(0,transition-dt);if(mode!=='play')return;elapsed+=dt;p.inv-=dt;p.shot-=dt;p.dashCd=Math.max(0,p.dashCd-dt);p.dash-=dt;p.recoil=Math.max(0,p.recoil-dt*8);p.hurtAnim=Math.max(0,p.hurtAnim-dt*4);p.trail=p.trail.filter(q=>(q.life-=dt)>0);
let mx=move.x+Number(keys.has('KeyD'))-Number(keys.has('KeyA')),my=move.y+Number(keys.has('KeyS'))-Number(keys.has('KeyW')),len=Math.hypot(mx,my);if(len>1){mx/=len;my/=len}if(p.dash>0){mx=p.dx*3.4;my=p.dy*3.4;burst(p.x,p.y,'#e9c77a',2,20)}else if(len>.1){p.dx=mx/(Math.hypot(mx,my)||1);p.dy=my/(Math.hypot(mx,my)||1)}p.animSpeed+=(Math.min(1,len)-p.animSpeed)*Math.min(1,dt*14);p.walk+=dt*(p.dash>0?26:13)*p.animSpeed;if(len>.1){p.facing={x:p.dx,y:p.dy};if(!mouse.down&&Math.hypot(aim.x,aim.y)<.15)p.aimAngle=Math.atan2(p.dy,p.dx)}if(p.dash>0)p.trail.push({x:p.x,y:p.y,life:.18});if(p.animSpeed>.4&&Math.sin(p.walk)> .92&&Math.sin(p.walk-13*dt)<=.92){burst(p.x,p.y+17,'#aab399',3,24);sfx('step',p.x);}moveBody(p,mx*p.speed*dt,my*p.speed*dt);
let ax=aim.x+Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft')),ay=aim.y+Number(keys.has('ArrowDown'))-Number(keys.has('ArrowUp'));let firing=Math.hypot(ax,ay)>.15;if(mouse.down){ax=mouse.x-p.x;ay=mouse.y-p.y;firing=true}if(firing){p.aimAngle=Math.atan2(ay,ax);p.facing={x:Math.cos(p.aimAngle),y:Math.sin(p.aimAngle)}}if(firing&&p.shot<=0){const a=Math.atan2(ay,ax);for(let i=0;i<p.multishot;i++)shoot(p.x,p.y-8,a+(i-(p.multishot-1)/2)*.15);p.shot=Math.max(.07,p.rate);sfx('shot',p.x)}
for(const e of [...room.enemies]){if(e.hp<=0)continue;e.t+=dt;e.cool-=dt;e.hit=Math.max(0,e.hit-dt);e.orbitHit-=dt;if(e.burn>0){e.burn-=dt;damage(e,6*dt)}e.slow=Math.max(0,e.slow-dt);const slow=e.slow>0?.55:1,a=Math.atan2(p.y-e.y,p.x-e.x),d=dist(e,p);let speed=0;
if(e.type==='crawler'||e.type==='baby'||e.type==='splitter')speed=e.type==='baby'?120:70+floor*8;
if(e.type==='wisp'){speed=50;moveBody(e,Math.cos(e.t*2)*30*dt,Math.sin(e.t*2)*30*dt,false);if(e.cool<=0){shoot(e.x,e.y,a,false,170+floor*15);e.cool=2.2}}
if(e.type==='eye'){if(d<190)speed=-40;if(e.cool<=0){for(let j=-1;j<=1;j++)shoot(e.x,e.y,a+j*.22,false,175);e.cool=2.3}}
if(e.type==='brute'){if(e.charge>0){moveBody(e,e.vx*dt,e.vy*dt);e.charge-=dt}else if(e.cool<=0){e.charge=.55;e.vx=Math.cos(a)*300;e.vy=Math.sin(a)*300;e.cool=2.6;burst(e.x,e.y,'#ef9b71',10)}else speed=e.cool<.6?0:35}
if(e.type==='boss'){speed=30+floor*8;if(e.cool<=0){e.phase++;const rage=e.hp<e.maxHp*.5;if(e.phase%3===0){for(let j=0;j<10+floor*2;j++)shoot(e.x,e.y,j*TAU/(10+floor*2)+e.t*.3,false,rage?210:150);sfx('enemy',e.x)}else if(e.phase%3===1){for(let j=-2;j<=2;j++)shoot(e.x,e.y,a+j*.18,false,220)}else if(room.enemies.filter(q=>q.hp>0).length<7){for(let j=0;j<floor+1;j++)room.enemies.push(enemy(floor===2?'crawler':'wisp',clamp(e.x+rnd(-130,130),180,940),clamp(e.y+rnd(-90,90),220,540)))}e.cool=rage?.85:1.5;if(floor===2){for(let j=0;j<6;j++)shoot(e.x,e.y,j*TAU/6-e.t,false,110)}}}
if(speed)moveBody(e,Math.cos(a)*speed*slow*dt,Math.sin(a)*speed*slow*dt,e.type!=='wisp');if(d<e.r+p.r-3)hurt(e.type==='boss'?2:1);for(let j=0;j<p.orbits;j++){const orb={x:p.x+Math.cos(time*2.6+j*TAU/p.orbits)*54,y:p.y+Math.sin(time*2.6+j*TAU/p.orbits)*54};if(dist(orb,e)<e.r+10&&e.orbitHit<=0){damage(e,16);e.orbitHit=.45;burst(orb.x,orb.y,'#ffcd79',5)}}}
for(const s of shots){s.life-=dt;if(s.friendly&&p.homing){let near=room.enemies.filter(e=>e.hp>0).sort((a,b)=>dist(s,a)-dist(s,b))[0];if(near){const a=Math.atan2(near.y-s.y,near.x-s.x),speed=Math.hypot(s.vx,s.vy);s.vx+= (Math.cos(a)*speed-s.vx)*Math.min(1,dt*4);s.vy+=(Math.sin(a)*speed-s.vy)*Math.min(1,dt*4)}}s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<95||s.x>1025||s.y<150||s.y>620){if(s.bounce>0){if(s.x<95||s.x>1025)s.vx*=-1;if(s.y<150||s.y>620)s.vy*=-1;s.bounce--;s.x=clamp(s.x,95,1025);s.y=clamp(s.y,150,620)}else s.life=0}for(const rock of room.rocks)if(dist(s,rock)<rock.r+s.r){s.life=0;burst(s.x,s.y,'#78897c',3,30);break}if(s.life<=0)continue;if(s.friendly){for(const e of room.enemies)if(e.hp>0&&!s.hit.has(e)&&dist(s,e)<e.r+s.r){s.hit.add(e);damage(e,s.damage);if(p.burn)e.burn=3;if(p.frost)e.slow=2;burst(s.x,s.y,'#f8d68a',5,60);if(!p.pierce){s.life=0;break}}}else if(dist(s,p)<p.r+s.r-3){hurt(1);s.life=0}}
shots=shots.filter(s=>s.life>0);for(const b of bombs){b.t-=dt;if(b.t<=0){shake=12;burst(b.x,b.y,'#ffd18a',60,300);sfx('explosion',b.x);for(const e of room.enemies)if(dist(e,b)<155)damage(e,p.bombDamage);room.rocks=room.rocks.filter(r=>dist(r,b)>155);shots=shots.filter(s=>s.friendly||dist(s,b)>190)}}bombs=bombs.filter(b=>b.t>0);
for(const item of room.pickups){if(item.taken||dist(p,item)>29)continue;if(item.price){if(item.block>elapsed)continue;if(p.coins<item.price){toast('Нужно '+item.price+' монет');item.block=elapsed+2;continue}if(item.type==='heal'&&p.hp>=p.maxHp)continue;p.coins-=item.price}if(item.type==='coin'){p.coins+=rnd(0,1)<.2?3:1;sfx('coin',item.x)}if(item.type==='heal'){if(p.hp>=p.maxHp)continue;p.hp=Math.min(p.maxHp,p.hp+2);sfx('heal')}if(item.type==='bomb'){p.bombs+=2;sfx('coin')}item.taken=true;if(item.type==='relic')choose('Сделка с тишиной');hud()}
if(!room.clear&&room.enemies.every(e=>e.hp<=0)){room.clear=true;clears++;shots=shots.filter(s=>s.friendly);p.coins+=3;burst(560,350,'#e5c991',30,180);sfx('clear');if(room.type==='boss'){if(floor===3){end(true);return}room.pickups.push({x:560,y:360,type:'stairs'});p.hp=Math.min(p.maxHp,p.hp+3);choose('Награда хранителя')}else{toast('Комната очищена · +3 монеты');if(clears%3===0)choose('Тьма оставила подарок')}}
if(mode==='play'&&room.clear){for(const item of room.pickups)if(item.type==='stairs'&&dist(p,item)<40){floor++;generate();toast('Глубже: '+floorNames[floor-1]);return}if(transition<=0){let d=-1;if(p.y<179&&Math.abs(p.x-560)<50)d=0;else if(p.x>998&&Math.abs(p.y-385)<52)d=1;else if(p.y>593&&Math.abs(p.x-560)<50)d=2;else if(p.x<122&&Math.abs(p.y-385)<52)d=3;if(d>=0&&room.doors[d])enter(room.doors[d],d)}}hud();}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill()}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function line(x,y,xx,yy,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(xx,yy);ctx.stroke()}
function flame(x,y,size=1,color='#ffc575'){ctx.save();ctx.translate(x,y);ctx.scale(size,size);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,-22);ctx.bezierCurveTo(15,-6,16,3,7,9);ctx.bezierCurveTo(-7,18,-15,3,-7,-9);ctx.quadraticCurveTo(-5,2,0,-22);ctx.fill();ellipse(0,3,4,7,'#fff1bb');ctx.restore()}
function person(x,y,scale=1,enemyType=null,hit=false,t=0){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ellipse(0,16,21,7,'#0006');const bob=Math.sin(t*5)*2;ctx.translate(0,bob);let color=enemyType?'#735366':'#345a5c',light=enemyType?'#a0788e':'#65908a';if(enemyType==='crawler'||enemyType==='baby'){for(let i=-1;i<=1;i++){line(-12,i*8, -24-Math.sin(t*7+i)*4,i*11+7,'#637769',4);line(12,i*8,24+Math.sin(t*7+i)*4,i*11+7,'#637769',4)}color='#526b54';light='#91a078'}if(enemyType==='brute'){color='#70504a';light='#a9836c'}if(enemyType==='splitter'){color='#56654c';light='#a0aa77'}if(enemyType==='boss'){color=floor===2?'#534c58':'#695256';light=floor===2?'#a590aa':'#b39882'}const g=ctx.createLinearGradient(-20,-30,20,22);g.addColorStop(0,hit?'#fbe6c6':light);g.addColorStop(.4,hit?'#fbe6c6':color);g.addColorStop(1,hit?'#eec0a0':'#1a2a2b');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-19,14);ctx.bezierCurveTo(-24,-8,-21,-32,0,-34);ctx.bezierCurveTo(21,-32,24,-8,19,14);ctx.quadraticCurveTo(9,21,0,17);ctx.quadraticCurveTo(-9,21,-19,14);ctx.fill();if(enemyType==='boss'){ctx.strokeStyle='#ccaf89';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-18,-23);ctx.lineTo(-24,-45);ctx.lineTo(-8,-34);ctx.lineTo(0,-49);ctx.lineTo(9,-34);ctx.lineTo(24,-45);ctx.lineTo(18,-23);ctx.stroke()}ellipse(0,-14,14,13,'#101b23');if(enemyType==='eye'){ellipse(0,-14,9,8,'#e8b68c');ellipse(Math.sin(t)*3,-14,3,6,'#382237')}else{ellipse(-6,-15,3,4,enemyType?'#f0a093':'#ffe5a5');ellipse(6,-15,3,4,enemyType?'#f0a093':'#ffe5a5')}if(!enemyType){ctx.fillStyle='#cf9d65';ctx.beginPath();ctx.moveTo(-15,0);ctx.lineTo(7,7);ctx.lineTo(18,26);ctx.lineTo(4,21);ctx.lineTo(-4,8);ctx.closePath();ctx.fill();flame(0,6,.4);line(-13,4,-18,10,'#80a69a',4)}else if(enemyType==='wisp'){ctx.fillStyle='#ab83b340';ctx.beginPath();ctx.moveTo(-15,13);ctx.lineTo(0,35+Math.sin(t*4)*7);ctx.lineTo(15,13);ctx.fill()}ctx.restore()}
function drawRoom(){const palette=floor===1?['#19292c','#293b3c','#3c4b46']:floor===2?['#242733','#373644','#4c4b4a']:['#2b2027','#403039','#51433f'];ctx.fillStyle='#10191d';ctx.fillRect(0,0,W,H);glow(560,370,620,palette[1]);ctx.fillStyle='#0c1317';ctx.fillRect(64,119,992,533);ctx.fillStyle=palette[0];ctx.fillRect(93,149,934,473);
for(let y=0;y<7;y++)for(let x=0;x<14;x++){let xx=95+x*66+(y%2?0:0),yy=150+y*67;ctx.fillStyle=(x+y)%3===0?palette[1]+'65':palette[1]+'35';ctx.fillRect(xx+2,yy+2,63,64);line(xx+4,yy+64,xx+62,yy+64,'#020c1235')}
ctx.strokeStyle='#b4b59614';ctx.lineWidth=2;ctx.strokeRect(119,174,882,420);ctx.strokeRect(125,180,870,408);ctx.beginPath();ctx.arc(560,383,118,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(560,383,106,0,TAU);ctx.stroke();for(let i=0;i<8;i++){const a=i*TAU/8;line(560+Math.cos(a)*90,383+Math.sin(a)*90,560+Math.cos(a)*116,383+Math.sin(a)*116,'#b4b59612')}
for(const d of room.decor){ctx.fillStyle='#acb8a014';ctx.fillRect(d.x,d.y,d.r*3,1);if(d.r>3.5){line(d.x,d.y,d.x+12,d.y+7,'#0003');line(d.x+12,d.y+7,d.x+9,d.y+15,'#0003')}}
for(let i=0;i<16;i++){ctx.fillStyle=i%2?palette[1]:palette[2];ctx.fillRect(66+i*62,112,59,36);ctx.fillStyle='#0b161a';ctx.fillRect(66+i*62,145,59,8);ctx.fillStyle=palette[1];ctx.fillRect(66+i*62,623,59,28);line(68+i*62,115,120+i*62,115,'#b2bb9b24',2)}for(let i=0;i<8;i++){ctx.fillStyle=palette[1];ctx.fillRect(65,151+i*59,27,56);ctx.fillRect(1028,151+i*59,27,56)}
for(let i=0;i<4;i++){if(!room.doors[i])continue;const x=i===1?1018:i===3?102:560,y=i===0?150:i===2?621:386;ctx.save();ctx.translate(x,y);ctx.rotate(i===1?Math.PI/2:i===2?Math.PI:i===3?-Math.PI/2:0);ctx.fillStyle='#080f13';ctx.fillRect(-40,-24,80,45);ctx.strokeStyle=room.clear?'#c8b27b':'#745459';ctx.lineWidth=4;ctx.strokeRect(-42,-25,84,48);if(!room.clear){for(let j=-25;j<=25;j+=12)line(j,-20,j,22,'#80686a',4);line(-35,5,35,5,'#80686a',5)}else{glow(0,12,62,room.doors[i].type==='boss'?'#db766230':'#e1bd6630');line(-24,10,0,-2,'#d2bd8455',2);line(0,-2,24,10,'#d2bd8455',2)}ctx.restore()}
for(const [x,y]of[[175,149],[940,149],[175,620],[940,620]]){glow(x,y,100,'#f9b95017');ctx.fillStyle='#383f37';ctx.fillRect(x-7,y-8,14,23);flame(x,y-12,.45+Math.sin(time*8+x)*.04);}
for(const rock of room.rocks){ellipse(rock.x+3,rock.y+12,rock.r+5,15,'#0006');ctx.fillStyle='#4b5c55';ctx.beginPath();for(let i=0;i<7;i++){const a=i*TAU/7;const x=rock.x+Math.cos(a)*rock.r,y=rock.y+Math.sin(a)*rock.r*.8; i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();line(rock.x-16,rock.y-8,rock.x+3,rock.y-16,'#809080',3);line(rock.x+3,rock.y-16,rock.x+17,rock.y-3,'#718170',2);ctx.fillStyle='#263c35';ctx.fillRect(rock.x-8,rock.y-6,9,4)}
for(const item of room.pickups){if(item.taken&&item.type!=='stairs')continue;const bob=Math.sin(time*3+item.x)*3;if(item.type==='stairs'){glow(item.x,item.y,90,'#d4ad6330');ellipse(item.x,item.y,43,27,'#070d11');for(let j=0;j<5;j++){ctx.strokeStyle='#b2996466';ctx.lineWidth=2;ctx.strokeRect(item.x-31+j*5,item.y-19+j*3,62-j*10,38-j*6)}ctx.fillStyle='#e6c782';ctx.font='12px Manrope, sans-serif';ctx.textAlign='center';ctx.fillText('СПУСТИТЬСЯ',item.x,item.y+51);continue}ellipse(item.x,item.y+8,14,5,'#0005');if(item.price){ctx.fillStyle='#4a4e41';ctx.fillRect(item.x-20,item.y+5,40,10)}glow(item.x,item.y,24,item.type==='coin'?'#ffc66322':'#92d9bc22');ctx.fillStyle=item.type==='heal'?'#ef927c':'#e9c87e';ctx.font='23px Georgia';ctx.textAlign='center';ctx.fillText({coin:'◈',heal:'♥',relic:'✧',bomb:'✹'}[item.type]||'',item.x,item.y+bob);if(item.price){ctx.font='12px Manrope, sans-serif';ctx.fillStyle='#e9c87e';ctx.fillText(item.price+' ◈',item.x,item.y+36)}}}
function draw(){ctx.save();ctx.clearRect(0,0,W,H);if(shake)ctx.translate(rnd(-shake,shake),rnd(-shake,shake));drawRoom();if(window.EmberArt)window.EmberArt.roomDetail(ctx,room,floor,time);for(const e of [...room.enemies].filter(e=>e.hp>0).sort((a,b)=>a.y-b.y)){if(e.type==='boss')glow(e.x,e.y,100,'#e3846819');if(e.type==='brute'&&e.cool<.6&&e.charge<=0){ctx.strokeStyle='#d3876755';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,35,0,TAU);ctx.stroke()}if(window.EmberArt)window.EmberArt.monster(ctx,e,time,floor);else person(e.x,e.y,e.type==='boss'?2.3:e.type==='brute'?1.35:e.type==='baby'?.6:1,e.type,e.hit>0,e.t);if(e.burn>0)flame(e.x,e.y-30,.5);if(e.slow>0){ctx.strokeStyle='#a0deef';ctx.strokeRect(e.x-12,e.y-15,24,24)}if(e.hp<e.maxHp&&e.type!=='boss'){ctx.fillStyle='#151b20';ctx.fillRect(e.x-19,e.y-43,38,3);ctx.fillStyle='#dca586';ctx.fillRect(e.x-19,e.y-43,38*e.hp/e.maxHp,3)}}
if(p){glow(p.x,p.y,130,'#f6c17114');if(p.shield){ctx.strokeStyle='#b3e1d57f';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(p.x,p.y-8,27,33,0,0,TAU);ctx.stroke()}if(window.EmberArt){for(const q of p.trail){ctx.save();ctx.globalAlpha=q.life/.18*.45;window.EmberArt.hero(ctx,{...p,x:q.x,y:q.y},time,true);ctx.restore()}window.EmberArt.hero(ctx,p,time)}else if(p.inv<=0||Math.floor(time*15)%2===0)person(p.x,p.y,1,null,false,time);for(let j=0;j<p.orbits;j++){let x=p.x+Math.cos(time*2.6+j*TAU/p.orbits)*54,y=p.y+Math.sin(time*2.6+j*TAU/p.orbits)*54;glow(x,y,28,'#ffc47455');flame(x,y,.55)}if(p.dashCd>0){ctx.strokeStyle='#efc98577';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y+3,26,-Math.PI/2,-Math.PI/2+TAU*(1-p.dashCd/p.dashMax));ctx.stroke()}}
for(const s of shots){line(s.x-s.vx*.025,s.y-s.vy*.025,s.x,s.y,s.friendly?'#f4c78844':'#e9858c44',s.r);ctx.shadowColor=s.friendly?'#ffcb77':'#ed7d93';ctx.shadowBlur=9;ellipse(s.x,s.y,s.r,s.r,s.friendly?(p.frost?'#b1e6ec':'#ffe1a0'):'#e78b97');ctx.shadowBlur=0;ellipse(s.x-1,s.y-1,s.r*.4,s.r*.4,'#fff3d7')}
for(const b of bombs){glow(b.x,b.y,150,'#ed9a3e0a');ellipse(b.x,b.y,10,11,b.t<.25?'#ffe1a0':'#54615b');flame(b.x+2,b.y-13,.3);ctx.strokeStyle='#edbd7b44';ctx.lineWidth=1;ctx.beginPath();ctx.arc(b.x,b.y,155*(1-b.t/1.1),0,TAU);ctx.stroke()}for(const f of particles){ctx.globalAlpha=clamp(f.life/f.max,0,1);ellipse(f.x,f.y,f.r,f.r,f.color)}ctx.globalAlpha=1;
const vignette=ctx.createRadialGradient(560,370,220,560,370,630);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#03090daa');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);for(let i=0;i<24;i++){const x=(i*147+Math.sin(time*.1+i)*20)%W,y=(i*79-time*(4+i%4)+H*10)%H;ellipse(x,y,1,1,'#e4d6a026')}if(mode!=='title')minimap();if(transition>0){ctx.fillStyle=`rgba(5,12,15,${transition*.8})`;ctx.fillRect(0,0,W,H)}ctx.restore();}
function minimap(){const unit=16,ox=966,oy=563;ctx.fillStyle='#091114bb';ctx.fillRect(ox-68,oy-65,140,116);for(const r of rooms){if(!r.seen&&!rooms.some(q=>q.seen&&q.doors.includes(r)))continue;let x=ox+r.x*unit,y=oy+r.y*unit;ctx.fillStyle=r===room?'#dfbd7b':r.seen?r.clear?'#657c72':'#485c5b':'#283738';ctx.fillRect(x-6,y-5,12,10);if(['boss','treasure','shop'].includes(r.type)){ctx.font='9px serif';ctx.textAlign='center';ctx.fillStyle=r.type==='boss'?'#f1a0a0':'#ecd09a';ctx.fillText(r.type==='boss'?'×':r.type==='shop'?'◈':'✧',x,y+3)}}ctx.fillStyle='#8e9e92';ctx.font='7px sans-serif';ctx.textAlign='center';ctx.fillText('КАРТА ГЛУБИНЫ',ox,oy+44)}
function pointer(e){const rect=canvas.getBoundingClientRect();mouse.x=(e.clientX-rect.left)/rect.width*W;mouse.y=(e.clientY-rect.top)/rect.height*H;mouse.active=true}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;pointer(e);mouse.down=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>mouse.down=false);canvas.addEventListener('pointercancel',()=>mouse.down=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','Escape'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(e.code==='Space'&&!e.repeat)dash();if(e.code==='KeyE'&&!e.repeat)bomb();keys.add(e.code)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();mouse.down=false;if(mode==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause()});
function stick(id,target){const el=$(id),knob=el.querySelector('i');let pid=null;function set(e){const rect=el.getBoundingClientRect(),dx=(e.clientX-rect.left-rect.width/2),dy=(e.clientY-rect.top-rect.height/2),d=Math.hypot(dx,dy),max=rect.width*.34;target.x=dx/Math.max(max,d);target.y=dy/Math.max(max,d);knob.style.transform=`translate(${target.x*max}px,${target.y*max}px)`}el.onpointerdown=e=>{if(pid!==null)return;e.preventDefault();pid=e.pointerId;el.setPointerCapture(pid);set(e)};el.onpointermove=e=>{if(e.pointerId===pid)set(e)};const reset=e=>{if(e.pointerId!==pid)return;pid=null;target.x=target.y=0;knob.style.transform=''};el.onpointerup=reset;el.onpointercancel=reset;el.onlostpointercapture=reset;}stick('moveStick',move);stick('aimStick',aim);
$('dashButton').onpointerdown=e=>{e.preventDefault();dash()};$('bombButton').onpointerdown=e=>{e.preventDefault();bomb()};$('pause').onclick=pause;$('sound').onclick=()=>{window.EmberAudio?.unlock();const box=$('audioSettings');box.hidden=!box.hidden;$('sound').setAttribute('aria-expanded',String(!box.hidden));if(!box.hidden&&mode==='play')pause()};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen()}catch{toast('Полный экран недоступен в этом браузере')}};
room=makeRoom(0,0,'start');room.clear=true;room.rocks=[{x:320,y:275,r:25},{x:800,y:445,r:25}];room.enemies=[enemy('wisp',760,320),enemy('crawler',850,480)];$('overlay').innerHTML=`<div class="intro"><div><div class="kicker">АТМОСФЕРНЫЙ ROGUELIKE · 01</div><h1>Пепельное<br><em>сердце.</em></h1><p>Последний огонь в мире, который забыл рассвет.<br>Спускайся глубже. Собирай реликвии.<br>Стань тем, чего боится темнота.</p><button id="start" class="primary">ЗАЖЕЧЬ ОГОНЬ <span style="margin-left:24px">↗</span></button><div class="meta">3 ГЛУБИНЫ · 17 РЕЛИКВИЙ · НОВЫЙ ПУТЬ КАЖДЫЙ РАЗ</div>${records.runs?`<div class="meta">Забегов: ${records.runs} · Побед: ${records.wins||0} · Рекорд: ${records.best||0}</div>`:''}</div><div class="sigil" aria-hidden="true"><div class="flame-art"></div><span class="sigil-label">ИЗ ПЕПЛА — В СВЕТ</span></div></div>`;$('start').onclick=start;
if(window.EmberAudio){const prefs=window.EmberAudio.preferences();$('audioEnabled').checked=prefs.enabled;$('musicVolume').value=Math.round(prefs.music*100);$('effectsVolume').value=Math.round(prefs.effects*100);const label=()=>{$('sound').textContent=$('audioEnabled').checked?'♫ Звук':'♫ Выкл.';$('musicValue').textContent=$('musicVolume').value+'%';$('effectsValue').textContent=$('effectsVolume').value+'%'};label();$('audioEnabled').onchange=()=>{window.EmberAudio.setting('enabled',$('audioEnabled').checked);label()};for(const [id,key]of [['musicVolume','music'],['effectsVolume','effects']]){$(id).oninput=()=>{window.EmberAudio.setting(key,Number($(id).value)/100);label()};$(id).onchange=()=>sfx('ui')}$('audioClose').onclick=()=>{$('audioSettings').hidden=true;$('sound').setAttribute('aria-expanded','false')};}

function frame(now){window.EmberAudio?.state({mode,floor,boss:room?.type==='boss'&&!room.clear,combat:!!room&&!room.clear,low:!!p&&p.hp<=2});let dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
// Explicit local test hook. Absent on the published origin.
if(location.hostname==='localhost'||location.hostname==='127.0.0.1')window.__emberTest={state:()=>({mode,floor,rooms,room,p,shots,kills,clears}),start,update,enter,damage,hurt,choose,end,dash,bomb};
})();
