(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],mobile=matchMedia('(max-width:640px)').matches;
const regions=[
{n:'Канада',p:41,lon:-106,lat:57,c:'cold',w:4,dens:1,airport:1,port:1},
{n:'США',p:342,lon:-99,lat:38,c:'temperate',w:4,dens:3,airport:1,port:1},
{n:'Мексика',p:131,lon:-102,lat:23,c:'warm',w:2,dens:3,airport:1,port:1},
{n:'Бразилия',p:218,lon:-52,lat:-10,c:'warm',w:2,dens:3,airport:1,port:1},
{n:'Аргентина',p:47,lon:-64,lat:-35,c:'temperate',w:3,dens:2,airport:1,port:1},
{n:'Великобритания',p:69,lon:-3,lat:55,c:'cool',w:4,dens:4,airport:1,port:1},
{n:'Франция',p:66,lon:2,lat:47,c:'cool',w:4,dens:3,airport:1,port:1},
{n:'Польша',p:38,lon:20,lat:52,c:'cool',w:3,dens:3,airport:1,port:0},
{n:'Египет',p:118,lon:30,lat:27,c:'hot',w:2,dens:4,airport:1,port:1},
{n:'Нигерия',p:238,lon:8,lat:9,c:'hot',w:1,dens:4,airport:1,port:1},
{n:'Кения',p:58,lon:37,lat:0,c:'hot',w:1,dens:2,airport:1,port:1},
{n:'ЮАР',p:64,lon:24,lat:-29,c:'warm',w:2,dens:2,airport:1,port:1},
{n:'Россия',p:144,lon:82,lat:61,c:'cold',w:3,dens:1,airport:1,port:1},
{n:'Саудовская Аравия',p:35,lon:45,lat:24,c:'hot',w:4,dens:1,airport:1,port:1},
{n:'Индия',p:1460,lon:79,lat:22,c:'hot',w:2,dens:5,airport:1,port:1},
{n:'Казахстан',p:21,lon:67,lat:48,c:'dry',w:3,dens:1,airport:1,port:0},
{n:'Китай',p:1410,lon:104,lat:35,c:'temperate',w:3,dens:4,airport:1,port:1},
{n:'Япония',p:123,lon:138,lat:37,c:'cool',w:4,dens:4,airport:1,port:1},
{n:'Таиланд',p:72,lon:101,lat:15,c:'warm',w:2,dens:3,airport:1,port:1},
{n:'Индонезия',p:286,lon:118,lat:-3,c:'warm',w:2,dens:4,airport:1,port:1},
{n:'Австралия',p:28,lon:134,lat:-25,c:'warm',w:4,dens:1,airport:1,port:1},
{n:'Новая Зеландия',p:5.3,lon:172,lat:-41,c:'cool',w:4,dens:1,airport:1,port:1},
{n:'Исландия',p:.4,lon:-19,lat:65,c:'cool',w:4,dens:1,airport:1,port:1}
];
const rawRoutes=[
[0,1,'ground'],[1,2,'ground'],[3,4,'ground'],[5,6,'ground'],[6,7,'ground'],[7,12,'ground'],
[8,9,'ground'],[8,10,'ground'],[9,10,'ground'],[10,11,'ground'],[12,15,'ground'],[12,16,'ground'],
[13,14,'ground'],[13,15,'ground'],[14,15,'ground'],[14,16,'ground'],[14,18,'ground'],[15,16,'ground'],[16,18,'ground'],
[1,5,'air'],[1,6,'air'],[3,8,'air'],[3,11,'air'],[6,8,'air'],[6,12,'air'],[6,13,'air'],
[8,13,'air'],[10,13,'air'],[12,17,'air'],[16,17,'air'],[16,19,'air'],[17,18,'air'],[18,20,'air'],[19,21,'air'],
[2,3,'sea'],[1,5,'sea'],[0,22,'sea'],[22,5,'sea'],[3,11,'sea'],[6,8,'sea'],[8,13,'sea'],
[14,19,'sea'],[16,17,'sea'],[18,19,'sea'],[19,20,'sea'],[20,21,'sea']
];
const routes=rawRoutes.map((r,i)=>({id:i,a:r[0],b:r[1],type:r[2]})),adj=regions.map(()=>[]);
routes.forEach(r=>{adj[r.a].push(r);adj[r.b].push(r)});
regions.forEach((r,i)=>Object.assign(r,{id:i,i:0,d:0,airClosed:false,seaClosed:false,borderClosed:false}));
const WORLD=regions.reduce((s,r)=>s+r.p,0);
const upgrades={spread:[
{id:'air1',name:'Воздушная передача I',cost:7,desc:'Инфекция чаще переносится пассажирами самолётов.',air:.38},
{id:'water1',name:'Водная передача I',cost:7,desc:'Инфекция лучше переживает морские перевозки и загрязнённую воду.',water:.38},
{id:'urban1',name:'Городская передача I',cost:6,desc:'Плотная городская среда ускоряет распространение.',inf:.12,dense:.12},
{id:'air2',name:'Воздушная передача II',cost:13,req:'air1',desc:'Дальние авиарейсы становятся заметно эффективнее.',air:.52},
{id:'water2',name:'Водная передача II',cost:13,req:'water1',desc:'Морские маршруты значительно чаще создают новые очаги.',water:.52},
{id:'urban2',name:'Городская передача II',cost:12,req:'urban1',desc:'Мегаполисы становятся особенно уязвимыми.',inf:.16,dense:.16},
{id:'aerosol',name:'Устойчивый аэрозоль',cost:19,req:'air2',desc:'Передача остаётся высокой даже при усилении санитарных мер.',inf:.14,air:.28},
{id:'biofilm',name:'Защитная биоплёнка',cost:19,req:'water2',desc:'Патоген дольше сохраняется во внешней среде.',inf:.1,water:.3}],
resist:[
{id:'cold1',name:'Холодоустойчивость I',cost:6,desc:'Холодный климат меньше замедляет распространение.',cold:.42},
{id:'heat1',name:'Жароустойчивость I',cost:6,desc:'Жаркий климат меньше замедляет распространение.',heat:.42},
{id:'drug1',name:'Устойчивость к терапии I',cost:9,desc:'Богатые страны хуже сдерживают распространение.',drug:.18,cureRes:.08},
{id:'stealth1',name:'Скрытое течение I',cost:8,desc:'Патоген дольше остаётся незамеченным.',stealth:.12},
{id:'cold2',name:'Холодоустойчивость II',cost:12,req:'cold1',desc:'Холод почти перестаёт быть препятствием.',cold:.42},
{id:'heat2',name:'Жароустойчивость II',cost:12,req:'heat1',desc:'Высокая температура почти перестаёт мешать распространению.',heat:.42},
{id:'drug2',name:'Устойчивость к терапии II',cost:16,req:'drug1',desc:'Лечение становится менее эффективным, а исследование лекарства замедляется.',drug:.2,cureRes:.18},
{id:'stealth2',name:'Скрытое течение II',cost:14,req:'stealth1',desc:'Международные службы позже оценивают реальный масштаб вспышки.',stealth:.18}],
symptom:[
{id:'cough',name:'Кашель',cost:4,desc:'Повышает заразность, но увеличивает заметность болезни.',inf:.08,sev:.04},
{id:'rash',name:'Сыпь',cost:5,desc:'Немного повышает тяжесть и ускоряет обнаружение.',sev:.06},
{id:'fever',name:'Лихорадка',cost:6,desc:'Повышает тяжесть заболевания и нагрузку на медицину.',sev:.1},
{id:'vomit',name:'Рвота',cost:7,req:'fever',desc:'Усиливает заразность и тяжесть заболевания.',inf:.06,sev:.09},
{id:'pneumonia',name:'Пневмония',cost:12,req:'cough',desc:'Сильно повышает тяжесть и добавляет летальность.',sev:.18,let:.0012},
{id:'neuro',name:'Неврологические осложнения',cost:14,req:'fever',desc:'Резко повышают тяжесть и реакцию систем здравоохранения.',sev:.2,let:.0008},
{id:'hemorrhage',name:'Геморрагический синдром',cost:20,req:'pneumonia',desc:'Опасное осложнение с высокой летальностью.',sev:.24,let:.003},
{id:'collapse',name:'Системный коллапс',cost:28,req:'hemorrhage',desc:'Финальная стадия с крайне высокой смертностью.',sev:.34,let:.006}]};
let state={day:0,dna:8,cure:0,speed:1,started:false,ended:false,selected:null,tab:'spread',name:'ZERO-01',detected:false,owned:{},history:[],lastAutoDNA:0,lastStory:0,lastMutation:0,treeKey:'',hidden:false};
const nodes=$('#nodes'),routeLayer=$('#routes'),effects=$('#effects');let projection=null,vehicles=[],animating=false;
function buildMap(){if(!window.d3||!window.topojson){positionGameLayers();return}projection=d3.geoEquirectangular().scale(151).translate([500,260]).clipExtent([[18,20],[982,500]]);const path=d3.geoPath(projection);$('#graticule').setAttribute('d',path(d3.geoGraticule10()));fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json').then(r=>r.json()).then(world=>{const f=topojson.feature(world,world.objects.countries).features;$('#geo').innerHTML=f.map(x=>`<path class="country" d="${path(x)}"></path>`).join('');$('#fallback').style.display='none';positionGameLayers()}).catch(positionGameLayers)}
function fallbackXY(lon,lat){return[500+lon*2.55,260-lat*2.5]}
function positionGameLayers(){regions.forEach(r=>{const p=projection?projection([r.lon,r.lat]):fallbackXY(r.lon,r.lat);r.x=p[0];r.y=p[1]});renderStaticLayers();render(true)}
function control(a,b,bend){const dx=b.x-a.x,dy=b.y-a.y;return{x:(a.x+b.x)/2-dy*bend,y:(a.y+b.y)/2+dx*bend}}
function curvePath(a,b,bend=.1){const c=control(a,b,bend);return`M ${a.x.toFixed(1)} ${a.y.toFixed(1)} Q ${c.x.toFixed(1)} ${c.y.toFixed(1)} ${b.x.toFixed(1)} ${b.y.toFixed(1)}`}
function qPoint(a,c,b,t){const u=1-t;return{x:u*u*a.x+2*u*t*c.x+t*t*b.x,y:u*u*a.y+2*u*t*c.y+t*t*b.y}}
function qTangent(a,c,b,t){return{x:2*(1-t)*(c.x-a.x)+2*t*(b.x-c.x),y:2*(1-t)*(c.y-a.y)+2*t*(b.y-c.y)}}
function routeBlocked(route){const a=regions[route.a],b=regions[route.b];if(route.type==='air')return a.airClosed||b.airClosed;if(route.type==='sea')return a.seaClosed||b.seaClosed;return a.borderClosed||b.borderClosed}
function renderStaticLayers(){routeLayer.innerHTML='';nodes.innerHTML='';routes.forEach(r=>{const a=regions[r.a],b=regions[r.b],bend=r.type==='air'?.09:r.type==='sea'?.05:.015;routeLayer.insertAdjacentHTML('beforeend',`<path class="route ${r.type}" data-route="${r.id}" d="${curvePath(a,b,bend)}"></path>`)});regions.forEach((r,i)=>nodes.insertAdjacentHTML('beforeend',`<g class="node" data-i="${i}" transform="translate(${r.x} ${r.y})"><circle class="outer" r="8.5"></circle><circle class="fill" r="2.8"></circle><text x="11" y="3">${r.n}</text></g>`));$$('.node').forEach(n=>n.onclick=()=>select(+n.dataset.i));if(state.selected!==null)$$('.node').forEach(n=>n.classList.toggle('selected',+n.dataset.i===state.selected))}
function fmt(v){if(v<.001)return'0';if(v<1)return Math.max(1,Math.round(v*1000)).toLocaleString('ru-RU')+' тыс.';if(v<1000)return Math.round(v).toLocaleString('ru-RU')+' млн';return(v/1000).toFixed(v>3000?2:1).replace('.',',')+' млрд'}
function total(k){return regions.reduce((s,r)=>s+r[k],0)}
function own(id){return!!state.owned[id]}
function stats(){let s={inf:1,air:1,water:1,cold:0,heat:0,drug:0,dense:0,stealth:0,cureRes:0,sev:0,let:0};Object.values(upgrades).flat().forEach(u=>{if(!own(u.id))return;Object.keys(s).forEach(k=>{if(u[k])s[k]+=u[k]})});return s}
function addHistory(kind,text){state.history.unshift({day:Math.floor(state.day),kind,text});if(state.history.length>100)state.history.pop()}
function log(text,kind='Событие'){addHistory(kind,text);const box=$('#events');box.insertAdjacentHTML('afterbegin',`<div class="event"><time>День ${Math.floor(state.day)}</time><span>${text}</span></div>`);while(box.children.length>4)box.lastElementChild.remove()}
function story(type,title,text){$('#storyType').textContent=type;$('#storyTitle').textContent=title;$('#storyText').textContent=text;$('#story').classList.add('show');clearTimeout(state.storyTimer);state.storyTimer=setTimeout(()=>$('#story').classList.remove('show'),4500)}
function renderHistory(){const box=$('#historyList');box.innerHTML=state.history.length?state.history.map(x=>`<div class="history-row"><time>День ${x.day}</time><b>${x.kind}</b><span>${x.text}</span></div>`).join(''):'<div class="history-row"><time>День 0</time><b>Архив</b><span>Событий пока нет.</span></div>'}
function climateName(c){return c==='cold'?'холодный климат':c==='hot'?'жаркий климат':c==='warm'?'тёплый климат':c==='dry'?'засушливый климат':c==='cool'?'прохладный климат':'умеренный климат'}
function updateRegionCard(){if(state.selected===null)return;const r=regions[state.selected],ratio=r.i/r.p;$('#regionName').textContent=r.n;$('#rPop').textContent=fmt(r.p);$('#rInf').textContent=fmt(r.i);$('#rDead').textContent=fmt(r.d);$('#rState').textContent=r.d>r.p*.55?'коллапс':ratio>.45?'кризис':ratio>.08?'эпидемия':r.i>.001?'вспышка':'стабильно';const tags=[`<span class="tag">${climateName(r.c)}</span>`,`<span class="tag">${r.w>=4?'богатая':r.w<=1?'бедная':'средний доход'}</span>`,`<span class="tag">${r.dens>=4?'высокая плотность':r.dens<=1?'низкая плотность':'средняя плотность'}</span>`];if(r.airport)tags.push(`<span class="tag${r.airClosed?' warn':''}">${r.airClosed?'аэропорт закрыт':'аэропорт'}</span>`);if(r.port)tags.push(`<span class="tag${r.seaClosed?' warn':''}">${r.seaClosed?'порт закрыт':'порт'}</span>`);if(r.borderClosed)tags.push('<span class="tag warn">границы закрыты</span>');$('#regionTags').innerHTML=tags.join('')}
function select(i){if(state.selected!==i){state.selected=i;$$('.node').forEach(n=>n.classList.toggle('selected',+n.dataset.i===i))}updateRegionCard()}
function childOwned(id){return Object.values(upgrades).flat().some(x=>x.req===id&&own(x.id))}
function renderTree(force=false){const key=[state.started,state.tab,Math.floor(state.dna),Object.keys(state.owned).sort().join(',')].join('|');if(!force&&key===state.treeKey)return;state.treeKey=key;const box=$('#tree');box.innerHTML='';upgrades[state.tab].forEach(u=>{const isOwned=own(u.id),locked=u.req&&!own(u.req),hasChild=isOwned&&childOwned(u.id),refund=Math.max(1,Math.floor(u.cost*.4)),b=document.createElement('button');b.className='upgrade'+(isOwned?' owned':'')+(locked?' locked':'');b.disabled=!state.started||locked||hasChild||(!isOwned&&state.dna<u.cost);const costText=isOwned?(hasChild?'Зависит':`↩ +${refund} ◈`):u.cost+' ◈';b.innerHTML=`<div class="upgrade-top"><b>${u.name}</b><span class="cost">${costText}</span></div><p>${u.desc}</p>${u.req?`<div class="req">Требуется: ${Object.values(upgrades).flat().find(x=>x.id===u.req).name}</div>`:''}`;b.onclick=()=>isOwned?devolve(u):buy(u);box.appendChild(b)})}
function buy(u){if(own(u.id)||state.dna<u.cost||(u.req&&!own(u.req)))return;state.dna-=u.cost;state.owned[u.id]=true;state.treeKey='';log(`Эволюция: ${u.name}`,'Эволюция');story('ЭВОЛЮЦИЯ',u.name,u.desc);render(true)}
function devolve(u){if(!own(u.id)||childOwned(u.id))return;delete state.owned[u.id];const refund=Math.max(1,Math.floor(u.cost*.4));state.dna+=refund;state.treeKey='';log(`Деэволюция: ${u.name}, возвращено ${refund} ◈`,'Эволюция');render(true)}
$$('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.treeKey='';$$('.tab').forEach(x=>x.classList.toggle('active',x===b));renderTree(true)});
$$('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;$$('.speed').forEach(x=>x.classList.toggle('active',x===b))});
function spawnDNA(i,amount=1){const r=regions[i];if(!Number.isFinite(r.x))return;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','dna-pop');g.setAttribute('transform',`translate(${r.x+(Math.random()-.5)*18} ${r.y-18+(Math.random()-.5)*10})`);g.innerHTML='<circle class="orb" r="13"></circle><text y="1">◈</text>';g.onclick=()=>{state.dna+=amount;g.remove();state.treeKey='';log(`Собрано ДНК: +${amount} ◈`,'ДНК');render(true)};effects.appendChild(g)}
function addVehicle(route,fromA=true){if(!route||routeBlocked(route)||!Number.isFinite(regions[route.a].x))return;if(route.type==='ground'||(mobile&&route.type==='sea'))return;const max=mobile?4:8;if(vehicles.length>=max)return;const a=regions[fromA?route.a:route.b],b=regions[fromA?route.b:route.a],bend=route.type==='air'?.09:.05,c=control(a,b,bend),g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','vehicle '+route.type);g.innerHTML=route.type==='air'?'<path d="M-9,-1.1 L-2,-1.1 L3,-6.5 L5.5,-6.5 L3.7,-1.1 L9.5,0 L3.7,1.1 L5.5,6.5 L3,6.5 L-2,1.1 L-9,1.1 L-5.5,0 Z"></path>':'<path fill="#b9e9ef" d="M-8,1 L8,1 L5,5 L-5,5 Z M-4,0 L-2,-5 L3,-5 L5,0 Z"></path>';effects.appendChild(g);vehicles.push({g,a,b,c,t:0,type:route.type,d:route.type==='air'?(mobile?6200:5400):9000});startAnimation()}
function startAnimation(){if(animating)return;animating=true;let last=performance.now();function frame(now){if(state.hidden){last=now;requestAnimationFrame(frame);return}const dt=Math.min(50,now-last);last=now;for(let i=vehicles.length-1;i>=0;i--){const p=vehicles[i];if(state.started&&!state.ended&&state.speed>0)p.t+=dt*state.speed/p.d;const t=Math.min(1,p.t),pt=qPoint(p.a,p.c,p.b,t),tg=qTangent(p.a,p.c,p.b,t),ang=Math.atan2(tg.y,tg.x)*180/Math.PI,drawAng=ang+(p.type==='air'?180:0);p.g.setAttribute('transform',`translate(${pt.x.toFixed(1)} ${pt.y.toFixed(1)}) rotate(${drawAng.toFixed(1)})`);if(p.t>=1){p.g.remove();vehicles.splice(i,1)}}if(vehicles.length)requestAnimationFrame(frame);else animating=false}requestAnimationFrame(frame)}
function trafficTick(){if(state.hidden||!state.started||state.ended||state.speed===0)return;const usable=routes.filter(r=>r.type!=='ground'&&!routeBlocked(r));if(!usable.length)return;const route=usable[Math.floor(Math.random()*usable.length)];addVehicle(route,Math.random()>.5)}
function wealthFactor(r,s){if(r.w>=4)return Math.min(1,.82+s.drug);if(r.w===1)return 1.08;return 1}
function climateFactor(r,s){let f=1;if(r.c==='cold'||r.c==='cool')f*=.58+Math.min(.42,s.cold);if(r.c==='hot'||r.c==='warm')f*=.62+Math.min(.38,s.heat);if(r.c==='dry')f*=.72+Math.min(.25,s.heat);return f}
function densityFactor(r,s){return 1+(r.dens-2)*(.045+s.dense*.12)}
function routeChance(route,s,ratio){let chance=.00135*(1+Math.min(7,ratio*75));if(route.type==='air')chance*=s.air;else if(route.type==='sea')chance*=s.water*.9;else chance*=1.3;return chance}
function maybeSpread(r,idx,s){const ratio=r.i/r.p;if(ratio<.00045)return;adj[idx].forEach(route=>{if(routeBlocked(route))return;const j=route.a===idx?route.b:route.a,to=regions[j];if(to.i>.001||to.d>to.p*.95)return;if(Math.random()<routeChance(route,s,ratio)){to.i=.002;spawnDNA(j,2);log(`${r.n} → ${to.n}: новая цепочка заражения`,'Распространение');story('НОВАЯ ВСПЫШКА',to.n,`Первые случаи связаны с перемещением из страны «${r.n}».`);addVehicle(route,route.a===idx)}})}
function responseStep(share,s){if(!state.detected)return;regions.forEach(r=>{const local=(r.i+r.d)/r.p,pressure=s.sev+share*.9+local*1.8;if(r.airport&&!r.airClosed&&pressure>.44&&Math.random()<.0015*(1+r.w*.12)){r.airClosed=true;log(`${r.n}: аэропорты ограничивают международные рейсы`,'Ограничения')}if(r.port&&!r.seaClosed&&pressure>.58&&Math.random()<.0012){r.seaClosed=true;log(`${r.n}: морские порты вводят карантин`,'Ограничения')}if(!r.borderClosed&&pressure>.72&&Math.random()<.0015){r.borderClosed=true;log(`${r.n}: сухопутные границы закрыты`,'Ограничения')}})}
function randomStory(share){if(state.day-state.lastStory<16||Math.random()>.012)return;state.lastStory=state.day;const pool=share<.03?[['Необычные случаи','Врачи нескольких стран сообщают о схожих симптомах.'],['Пассажиропоток растёт','Международные транспортные узлы работают на пределе.'],['Первые слухи','В социальных сетях обсуждают неизвестную инфекцию.']]:share<.3?[['Экстренный саммит','Страны координируют ограничения и обмен медицинскими данными.'],['Карантинные меры','Крупные города усиливают санитарный контроль.'],['Исследовательская коалиция','Лаборатории объединяют ресурсы для разработки лекарства.']]:[['Глобальный кризис','Системы здравоохранения многих стран перегружены.'],['Массовое закрытие границ','Международная мобильность резко сокращается.'],['Финальная гонка','Исследователи ускоряют последние этапы разработки лекарства.']];const x=pool[Math.floor(Math.random()*pool.length)];log(x[0]+': '+x[1],'Новости');story('МИРОВЫЕ НОВОСТИ',x[0],x[1])}
function mutationStep(){if(state.day-state.lastMutation<14||Math.random()>.0032)return;const candidates=upgrades.symptom.filter(u=>!own(u.id)&&(!u.req||own(u.req)));if(!candidates.length)return;const u=candidates[Math.floor(Math.random()*candidates.length)];state.owned[u.id]=true;state.lastMutation=state.day;state.treeKey='';log(`Спонтанная мутация: ${u.name}`,'Мутация');story('СПОНТАННАЯ МУТАЦИЯ',u.name,'Патоген самостоятельно приобрёл новый симптом.')}
function cureStep(s,share){if(!state.detected)return;const labs=regions.reduce((sum,r)=>sum+(r.i>0?r.w*.12:0),0),research=(.0014+s.sev*.0026+share*.005)*(1+labs)*(1-s.stealth)*(1-s.cureRes);state.cure=Math.min(100,state.cure+Math.max(.00035,research));[[25,'25%','Исследовательские центры переходят к активной фазе.','c25'],[50,'50%','Половина работы над лекарством завершена.','c50'],[75,'75%','Начинаются масштабные испытания.','c75'],[100,'100%','Лекарство готово к массовому применению.','c100']].forEach(x=>{if(state.cure>=x[0]&&!state[x[3]]){state[x[3]]=true;log(`Исследование лекарства: ${x[1]}`,'Лекарство');story('ИССЛЕДОВАНИЕ',`Лекарство: ${x[1]}`,x[2])}})}
function step(){if(state.hidden||!state.started||state.ended||state.speed===0)return;for(let n=0;n<state.speed;n++){state.day+=mobile?.5:.42;const s=stats();let newCases=0;regions.forEach((r,idx)=>{if(r.i<=0)return;const healthy=Math.max(0,r.p-r.i-r.d),ratio=healthy/r.p;let growth=Math.min(healthy,r.i*.047*s.inf*climateFactor(r,s)*densityFactor(r,s)*wealthFactor(r,s)*ratio);if(state.cure>70)growth*=1-Math.min(.28,(state.cure-70)/30*.28);if(state.cure>=100)growth-=r.i*(.075+.018*r.w);growth=Math.max(-r.i,growth);r.i+=growth;newCases+=Math.max(0,growth);const deaths=Math.min(r.i,r.i*s.let*(.5+.5*Math.min(1,r.i/r.p*3)));r.i-=deaths;r.d+=deaths;maybeSpread(r,idx,s)});const inf=total('i'),dead=total('d'),share=inf/WORLD;state.dna+=Math.min(.14,newCases*.0011);if(state.day-state.lastAutoDNA>10&&inf>.02){state.lastAutoDNA=state.day;const c=regions.filter(r=>r.i>.001);if(c.length)spawnDNA(c[Math.floor(Math.random()*c.length)].id,1)}if(!state.detected&&(inf>.35||s.sev>.14)){state.detected=true;log('Международные службы официально признают новую угрозу','Открытие');story('УГРОЗА ОБНАРУЖЕНА',state.name,'Начинается международное исследование лекарства.')}responseStep(share,s);randomStory(share);mutationStep();cureStep(s,share);const alive=Math.max(0,WORLD-dead);if(alive<.001){end(true);break}if(state.cure>=100&&inf<.002){end(false);break}}render()}
function render(force=false){const inf=total('i'),dead=total('d'),healthy=Math.max(0,WORLD-inf-dead),s=stats();$('#healthy').textContent=fmt(healthy);$('#infected').textContent=fmt(inf);$('#dead').textContent=fmt(dead);$('#dna').textContent=Math.floor(state.dna)+' ◈';$('#day').textContent='День '+Math.floor(state.day);$('#cureText').textContent=Math.floor(state.cure)+'%';$('#cureBar').style.width=state.cure+'%';$('#infectBar').style.width=Math.min(100,(s.inf-1)*100+(s.air+s.water-2)*18+18)+'%';$('#severityBar').style.width=Math.min(100,s.sev*150+5)+'%';$('#lethalBar').style.width=Math.min(100,s.let*9000+4)+'%';updateRegionCard();$$('.node').forEach(n=>{const r=regions[+n.dataset.i],ratio=(r.i+r.d)/r.p;n.classList.toggle('infected',r.i>.001);n.classList.toggle('deadly',r.d>r.i&&r.d>r.p*.08);n.classList.toggle('closed',r.airClosed||r.seaClosed||r.borderClosed);n.querySelector('.fill').setAttribute('r',String(2.8+Math.min(7.2,ratio*11)))});$$('.route').forEach(l=>{const r=routes[+l.dataset.route],a=regions[r.a],b=regions[r.b];l.classList.toggle('active',a.i>.01||b.i>.01);l.classList.toggle('closed',routeBlocked(r))});renderTree(force)}
function end(win){state.ended=true;state.speed=0;const inf=total('i'),dead=total('d');$('#resultOverlay').classList.remove('hidden');$('#resultKicker').textContent=win?'МИР ВЫМЕР':'ВСПЫШКА ОСТАНОВЛЕНА';$('#resultTitle').textContent=win?'ПОБЕДА':'ПОРАЖЕНИЕ';$('#resultText').textContent=win?`${state.name} уничтожил всё население моделируемых стран. Живых не осталось.`:`Лекарство завершено, а последние активные очаги ${state.name} исчезли.`;$('#resultScore').textContent=`День ${Math.floor(state.day)} • заражено ${fmt(inf)} • погибло ${fmt(dead)} • эволюций ${Object.keys(state.owned).length}`}
regions.forEach((r,i)=>$('#startSelect').insertAdjacentHTML('beforeend',`<option value="${i}">${r.n}</option>`));$('#startSelect').value='3';
$('#startBtn').onclick=()=>{const idx=+$('#startSelect').value;state.name=($('#nameInput').value||'ZERO-01').trim().slice(0,22)||'ZERO-01';$('#pathogenName').textContent=state.name;regions[idx].i=.02;state.started=true;state.selected=null;state.treeKey='';$('#startOverlay').classList.add('hidden');select(idx);spawnDNA(idx,2);log(`${state.name}: первые случаи зарегистрированы — ${regions[idx].n}`,'Начало');story('НУЛЕВОЙ ДЕНЬ',regions[idx].n,`Образец «${state.name}» начал распространяться.`);render(true)};
$('#historyBtn').onclick=()=>{renderHistory();$('#historyOverlay').classList.remove('hidden')};$('#closeHistory').onclick=()=>$('#historyOverlay').classList.add('hidden');$('#historyOverlay').onclick=e=>{if(e.target===$('#historyOverlay'))$('#historyOverlay').classList.add('hidden')};document.addEventListener('visibilitychange',()=>state.hidden=document.hidden);
positionGameLayers();buildMap();render(true);setInterval(step,mobile?780:640);setInterval(trafficTick,mobile?2800:2100);
})();