(()=>{
'use strict';
const $=s=>document.querySelector(s), mobile=matchMedia('(max-width:640px)').matches, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const fx=document.createElement('div');fx.className='game-fx-layer';document.body.appendChild(fx);

const videoCss=document.createElement('style');
videoCss.textContent=`
.pathogen-video-shell{position:relative!important;width:124px!important;height:124px!important;flex:0 0 124px!important;border-radius:22px!important;overflow:hidden!important;background:#06100b!important;border:1px solid #4f7f59!important;box-shadow:inset 0 0 0 1px #9bff7a16,0 0 28px #78ff6f25!important;isolation:isolate}
.pathogen-video{position:absolute;inset:-7%;width:114%;height:114%;object-fit:cover;display:block;transform:scale(1.03);filter:saturate(1.14) contrast(1.08) brightness(.94);transition:filter .45s ease,transform .45s ease}
.pathogen-video-vignette{position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 68% 52%,transparent 0 25%,#04100a12 47%,#010703b8 100%),linear-gradient(180deg,#adff8a12,transparent 26%,transparent 73%,#0008);box-shadow:inset 0 0 32px #0009;z-index:2}
.pathogen-video-scan{position:absolute;left:4%;right:4%;height:1px;top:10%;z-index:3;background:linear-gradient(90deg,transparent,#baff85aa,transparent);box-shadow:0 0 8px #aaff76;opacity:.55;animation:specimenScan 4.2s ease-in-out infinite}
.pathogen-video-ring{position:absolute;z-index:3;border:1px solid #9cff852e;border-radius:50%;pointer-events:none}.pathogen-video-ring.r1{inset:8px;animation:specimenRing 5.5s ease-in-out infinite}.pathogen-video-ring.r2{inset:16px;border-style:dashed;animation:specimenSpin 15s linear infinite}
.pathogen-video-label{position:absolute;left:9px;bottom:7px;z-index:4;font:700 7px/1.1 Inter,system-ui,sans-serif;letter-spacing:.16em;color:#d7ffc1;text-shadow:0 0 8px #9cff77;background:#05100aa8;border:1px solid #91dc7c2f;border-radius:4px;padding:4px 5px;backdrop-filter:blur(3px)}
.pathogen-video-shell[data-stage="1"] .pathogen-video{filter:saturate(1.22) contrast(1.1) brightness(.97)}.pathogen-video-shell[data-stage="2"] .pathogen-video{filter:saturate(1.3) contrast(1.12) brightness(1.01) hue-rotate(5deg)}.pathogen-video-shell[data-stage="3"] .pathogen-video{filter:saturate(1.42) contrast(1.15) brightness(1.04) hue-rotate(10deg)}.pathogen-video-shell[data-stage="4"] .pathogen-video{filter:saturate(1.55) contrast(1.18) brightness(1.07) hue-rotate(14deg)}
.pathogen-video-shell.mutating{animation:videoMutate .95s cubic-bezier(.16,.86,.25,1);box-shadow:inset 0 0 0 1px #d9ff9b66,0 0 46px #aaff6c65!important}.pathogen-video-shell.mutating .pathogen-video{transform:scale(1.15) rotate(.8deg);filter:saturate(1.75) contrast(1.24) brightness(1.16) hue-rotate(12deg)}.pathogen-video-shell.fed{animation:videoFed .52s ease-out}
@keyframes specimenScan{0%,100%{top:9%;opacity:.25}45%,55%{opacity:.8}50%{top:88%}}@keyframes specimenRing{0%,100%{transform:scale(.96);opacity:.28}50%{transform:scale(1.04);opacity:.7}}@keyframes specimenSpin{to{transform:rotate(360deg)}}@keyframes videoMutate{0%{transform:scale(1)}25%{transform:scale(1.08) rotate(-1.5deg)}50%{transform:scale(.96) rotate(1.2deg)}78%{transform:scale(1.04)}100%{transform:scale(1)}}@keyframes videoFed{0%{filter:brightness(1)}35%{filter:brightness(1.42)}100%{filter:brightness(1)}}
@media(max-width:640px){.pathogen-video-shell{width:92px!important;height:92px!important;flex-basis:92px!important;border-radius:18px!important}.pathogen-video-label{font-size:5.5px;left:6px;bottom:5px}.pathogen-video-ring.r2{display:none}.pathogen-video-scan{animation-duration:3.4s}}
@media(prefers-reduced-motion:reduce){.pathogen-video-scan,.pathogen-video-ring{animation:none!important}}
`;
document.head.appendChild(videoCss);

function ensureInfectionRings(){document.querySelectorAll('#nodes .node').forEach(n=>{if(n.querySelector('.infection-ring'))return;const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','infection-ring');c.setAttribute('r','8.5');n.insertBefore(c,n.firstChild)})}
ensureInfectionRings();const nodes=document.querySelector('#nodes');if(nodes)new MutationObserver(ensureInfectionRings).observe(nodes,{childList:true});
function burst(x,y,type='dna',label=''){if(reduced)return;const wrap=document.createElement('div');wrap.className='fx-burst '+type;wrap.style.left=x+'px';wrap.style.top=y+'px';const count=mobile?8:14;let html='<i class="fx-core"></i><i class="fx-ring"></i>';for(let i=0;i<count;i++){const a=Math.PI*2/count*i+(Math.random()-.5)*.3,d=(mobile?30:42)+Math.random()*(mobile?22:34);html+=`<i class="fx-particle" style="--dx:${Math.cos(a)*d}px;--dy:${Math.sin(a)*d}px;--delay:${i*10}ms"></i>`}if(label)html+=`<b class="fx-label">${label}</b>`;wrap.innerHTML=html;fx.appendChild(wrap);setTimeout(()=>wrap.remove(),1100)}
function pulseSpecimen(cls='fed',ms=560){const p=$('#pathogenVisual');if(!p)return;p.classList.remove(cls);void p.offsetWidth;p.classList.add(cls);setTimeout(()=>p.classList.remove(cls),ms)}
function dnaPickup(e){const orb=e.target.closest?.('.dna-pop');if(!orb)return;burst(e.clientX,e.clientY,'dna','+ ДНК');pulseSpecimen('fed',560);const metric=$('.metric.dna');if(metric){metric.classList.remove('dna-flash');void metric.offsetWidth;metric.classList.add('dna-flash');setTimeout(()=>metric.classList.remove('dna-flash'),620)}}
document.addEventListener('pointerdown',dnaPickup,{passive:true,capture:true});
function mutationFx(btn){const r=btn.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+Math.min(r.height/2,70);burst(x,y,'mutation','МУТАЦИЯ');document.body.classList.remove('mutation-flash');void document.body.offsetWidth;document.body.classList.add('mutation-flash');const p=$('#pathogenVisual'),v=$('#pathogenVideo');if(p){const stage=Math.min(4,(+p.dataset.stage||0)+1);p.dataset.stage=stage;p.classList.remove('mutating');void p.offsetWidth;p.classList.add('mutating');setTimeout(()=>p.classList.remove('mutating'),1000)}if(v){const old=v.playbackRate||1;v.playbackRate=1.65;v.play().catch(()=>{});setTimeout(()=>v.playbackRate=old,1050)}setTimeout(()=>document.body.classList.remove('mutation-flash'),900)}
document.addEventListener('click',e=>{const btn=e.target.closest?.('.upgrade');if(!btn||btn.disabled||btn.classList.contains('owned'))return;mutationFx(btn)},{capture:true});
const v=$('#pathogenVideo');if(v){v.muted=true;v.loop=true;v.playsInline=true;const tryPlay=()=>v.play().catch(()=>{});tryPlay();document.addEventListener('pointerdown',tryPlay,{once:true,passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)v.pause();else tryPlay()})}
})();