(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],mobile=matchMedia('(max-width:640px)').matches;
const regions=[
{n:'Канада',p:41,lon:-106,lat:57,c:'cold',w:3,air:1},{n:'США',p:342,lon:-99,lat:38,c:'temperate',w:4,air:1},{n:'Мексика',p:131,lon:-102,lat:23,c:'warm',w:2,air:1},{n:'Бразилия',p:218,lon:-52,lat:-10,c:'warm',w:2,air:1},{n:'Аргентина',p:47,lon:-64,lat:-35,c:'temperate',w:2,air:1},{n:'Британия',p:69,lon:-3,lat:55,c:'cool',w:4,air:1},{n:'Западная Европа',p:390,lon:9,lat:49,c:'cool',w:4,air:1},{n:'Восточная Европа',p:285,lon:26,lat:50,c:'cool',w:3,air:1},{n:'Северная Африка',p:275,lon:15,lat:27,c:'hot',w:2,air:1},{n:'Западная Африка',p:435,lon:-2,lat:10,c:'hot',w:1,air:1},{n:'Восточная Африка',p:510,lon:37,lat:2,c:'hot',w:1,air:1},{n:'Южная Африка',p:72,lon:24,lat:-29,c:'warm',w:2,air:1},{n:'Север Евразии',p:145,lon:82,lat:61,c:'cold',w:3,air:1},{n:'Ближний Восток',p:420,lon:45,lat:29,c:'hot',w:3,air:1},{n:'Индия',p:1460,lon:79,lat:22,c:'hot',w:2,air:1},{n:'Центральная Азия',p:285,lon:67,lat:43,c:'dry',w:2,air:1},{n:'Китай',p:1410,lon:104,lat:35,c:'temperate',w:3,air:1},{n:'Япония',p:123,lon:138,lat:37,c:'cool',w:4,air:1},{n:'Юго-Восточная Азия',p:690,lon:103,lat:12,c:'warm',w:2,air:1},{n:'Индонезия',p:285,lon:118,lat:-3,c:'warm',w:2,air:1},{n:'Австралия',p:28,lon:134,lat:-25,c:'warm',w:4,air:1},{n:'Новая Зеландия',p:5,lon:172,lat:-41,c:'cool',w:4,air:1},{n:'Гренландия',p:.06,lon:-42,lat:72,c:'cold',w:3,air:1}];
const rawRoutes=[[0,1,'ground'],[1,2,'ground'],[2,3,'air'],[3,4,'ground'],[1,5,'air'],[1,6,'air'],[3,8,'air'],[3,11,'air'],[5,6,'ground'],[5,22,'air'],[6,7,'ground'],[6,8,'air'],[6,12,'air'],[6,13,'air'],[7,12,'ground'],[7,13,'ground'],[8,9,'ground'],[8,10,'ground'],[8,13,'air'],[9,10,'ground'],[9,3,'air'],[10,11,'ground'],[10,13,'air'],[11,20,'air'],[12,15,'ground'],[12,16,'ground'],[12,17,'air'],[13,14,'ground'],[13,15,'ground'],[14,15,'ground'],[14,16,'ground'],[14,18,'ground'],[14,19,'air'],[15,16,'ground'],[16,17,'air'],[16,18,'ground'],[16,19,'air'],[17,18,'air'],[18,19,'ground'],[18,20,'air'],[19,20,'air'],[19,21,'air'],[20,21,'air'],[0,22,'air']];
const routes=rawRoutes.map((r,i)=>({id:i,a:r[0],b:r[1],type:r[2]}));regions.forEach((r,i)=>Object.assign(r,{id:i,i:0,d:0,closed:false}));const WORLD=regions.reduce((s,r)=>s+r.p,0);
const upgrades={spread:[
{id:'urban1',name:'Городское распространение I',cost:5,desc:'Инфекция быстрее передаётся в густонаселённых районах.',inf:.12},
{id:'air1',name:'Воздушные маршруты I',cost:7,desc:'Перелёты чаще переносят инфекцию между регионами.',air:.38},
{id:'transit1',name:'Международный транзит I',cost:8,desc:'Крупные транспортные узлы повышают шанс дальнего распространения.',air:.3},
{id:'urban2',name:'Городское распространение II',cost:11,req:'urban1',desc:'Передача инфекции в крупных городах становится ещё быстрее.',inf:.16},
{id:'air2',name:'Воздушные маршруты II',cost:13,req:'air1',desc:'Международные перелёты эффективнее разносят инфекцию.',air:.5},
{id:'transit2',name:'Международный транзит II',cost:14,req:'transit1',desc:'Сложные маршруты с пересадками заметно усиливают глобальное распространение.',air:.42},
{id:'network',name:'Глобальная транспортная сеть',cost:20,req:'urban2',desc:'Повышает скорость передачи внутри регионов и между ними.',inf:.2,air:.3}],
resist:[
{id:'cold1',name:'Адаптация к холоду I',cost:6,desc:'Инфекция лучше распространяется в странах с холодным климатом.',cold:.45},
{id:'heat1',name:'Адаптация к жаре I',cost:6,desc:'Инфекция лучше распространяется в странах с жарким климатом.',heat:.45},
{id:'stealth1',name:'Скрытое течение I',cost:9,desc:'Вспышку сложнее заметить, поэтому исследования лекарства начинаются медленнее.',stealth:.14},
{id:'cold2',name:'Адаптация к холоду II',cost:12,req:'cold1',desc:'Холодный климат почти перестаёт замедлять распространение инфекции.',cold:.45},
{id:'heat2',name:'Адаптация к жаре II',cost:12,req:'heat1',desc:'Жаркий климат почти перестаёт замедлять распространение инфекции.',heat:.45},
{id:'stealth2',name:'Скрытое течение II',cost:15,req:'stealth1',desc:'Мир ещё дольше недооценивает масштаб вспышки.',stealth:.18},
{id:'resistmed',name:'Устойчивость к лечению',cost:21,req:'stealth2',desc:'Разработка и применение лекарства требуют больше времени.',cureRes:.3}],
symptom:[
{id:'cough',name:'Кашель',cost:4,desc:'Повышает заразность, но делает вспышку заметнее.',inf:.08,sev:.05},
{id:'fever',name:'Лихорадка',cost:6,desc:'Повышает тяжесть заболевания и ускоряет обнаружение вспышки.',sev:.1},
{id:'fatigue',name:'Слабость',cost:5,desc:'Умеренно повышает тяжесть симптомов.',sev:.06},
{id:'pneumonia',name:'Пневмония',cost:12,req:'cough',desc:'Сильно повышает тяжесть заболевания и немного увеличивает смертность.',sev:.18,let:.0012},
{id:'neuro',name:'Неврологические осложнения',cost:14,req:'fever',desc:'Резко повышают тяжесть заболевания и ускоряют реакцию мира.',sev:.22,let:.001},
{id:'shock',name:'Системный шок',cost:20,req:'pneumonia',desc:'Заметно повышает смертность. Опасно развивать слишком рано.',sev:.28,let:.003},
{id:'collapse',name:'Критическая стадия',cost:28,req:'shock',desc:'Финальная тяжёлая стадия с очень высокой смертностью.',sev:.35,let:.006}]};
let state={day:0,dna:8,cure:0,speed:1,started:false,ended:false,selected:null,tab:'spread',name:'ZERO-01',detected:false,owned:{},history:[],lastAutoDNA:0,lastStory:0,closures:0,treeKey:'',hidden:false};
const nodes=$('#nodes'),routeLayer=$('#routes'),effects=$('#effects');let projection=null,planes=[],animating=false;
function buildMap(){if(!window.d3||!window.topojson){positionGameLayers();return}projection=d3.geoEquirectangular().scale(151).translate([500,260]).clipExtent([[18,20],[982,500]]);const path=d3.geoPath(projection);$('#graticule').setAttribute('d',path(d3.geoGraticule10()));fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json').then(r=>r.json()).then(world=>{const f=topojson.feature(world,world.objects.countries).features;$('#geo').innerHTML=f.map(x=>`<path class="country" d="${path(x)}"></path>`).join('');$('#fallback').style.display='none';positionGameLayers()}).catch(positionGameLayers)}
function fallbackXY(lon,lat){return[500+lon*2.55,260-lat*2.5]}function positionGameLayers(){regions.forEach(r=>{const p=projection?projection([r.lon,r.lat]):fallbackXY(r.lon,r.lat);r.x=p[0];r.y=p[1]});renderStaticLayers();render(true)}
function control(a,b,bend){const dx=b.x-a.x,dy=b.y-a.y;return{x:(a.x+b.x)/2-dy*bend,y:(a.y+b.y)/2+dx*bend}}function curvePath(a,b,bend=.1){const c=control(a,b,bend);return`M ${a.x.toFixed(1)} ${a.y.toFixed(1)} Q ${c.x.toFixed(1)} ${c.y.toFixed(1)} ${b.x.toFixed(1)} ${b.y.toFixed(1)}`}function qPoint(a,c,b,t){const u=1-t;return{x:u*u*a.x+2*u*t*c.x+t*t*b.x,y:u*u*a.y+2*u*t*c.y+t*t*b.y}}function qTangent(a,c,b,t){return{x:2*(1-t)*(c.x-a.x)+2*t*(b.x-c.x),y:2*(1-t)*(c.y-a.y)+2*t*(b.y-c.y)}}
function renderStaticLayers(){routeLayer.innerHTML='';nodes.innerHTML='';routes.forEach(r=>{let a=regions[r.a],b=regions[r.b];routeLayer.insertAdjacentHTML('beforeend',`<path class="route ${r.type}" data-route="${r.id}" d="${curvePath(a,b,r.type==='air'?.09:.015)}"></path>`)});regions.forEach((r,i)=>nodes.insertAdjacentHTML('beforeend',`<g class="node" data-i="${i}" transform="translate(${r.x} ${r.y})"><circle class="outer" r="8.5"></circle><circle class="fill" r="2.8"></circle><text x="11" y="3">${r.n}</text></g>`));$$('.node').forEach(n=>n.onclick=()=>select(+n.dataset.i));if(state.selected!==null)$$('.node').forEach(n=>n.classList.toggle('selected',+n.dataset.i===state.selected))}
function fmt(v){if(v<.001)return'0';if(v<1)return Math.max(1,Math.round(v*1000)).toLocaleString('ru-RU')+' тыс.';if(v<1000)return Math.round(v).toLocaleString('ru-RU')+' млн';return(v/1000).toFixed(v>3000?2:1).replace('.',',')+' млрд'}function total(k){return regions.reduce((s,r)=>s+r[k],0)}function own(id){return!!state.owned[id]}function stats(){let s={inf:1,air:1,cold:0,heat:0,stealth:0,cureRes:0,sev:0,let:0};Object.values(upgrades).flat().forEach(u=>{if(!own(u.id))return;['inf','air','cold','heat','stealth','cureRes','sev','let'].forEach(k=>{if(u[k])s[k]+=u[k]})});return s}
function addHistory(kind,text){state.history.unshift({day:Math.floor(state.day),kind,text});if(state.history.length>80)state.history.pop()}function log(text,kind='Событие'){addHistory(kind,text);let box=$('#events');box.insertAdjacentHTML('afterbegin',`<div class="event"><time>День ${Math.floor(state.day)}</time><span>${text}</span></div>`);while(box.children.length>4)box.lastElementChild.remove()}function story(type,title,text){$('#storyType').textContent=type;$('#storyTitle').textContent=title;$('#storyText').textContent=text;$('#story').classList.add('show');clearTimeout(state.storyTimer);state.storyTimer=setTimeout(()=>$('#story').classList.remove('show'),4500)}function renderHistory(){let box=$('#historyList');box.innerHTML=state.history.length?state.history.map(x=>`<div class="history-row"><time>День ${x.day}</time><b>${x.kind}</b><span>${x.text}</span></div>`).join(''):'<div class="history-row"><time>День 0</time><b>Архив</b><span>Событий пока нет.</span></div>'}
function updateRegionCard(){if(state.selected===null)return;let r=regions[state.selected],ratio=r.i/r.p;$('#regionName').textContent=r.n;$('#rPop').textContent=fmt(r.p);$('#rInf').textContent=fmt(r.i);$('#rDead').textContent=fmt(r.d);$('#rState').textContent=r.d>r.p*.55?'коллапс':ratio>.45?'кризис':ratio>.08?'эпидемия':r.i>.001?'вспышка':'стабильно';let climate=r.c==='cold'?'холодный климат':r.c==='hot'?'жаркий климат':r.c==='warm'?'тёплый климат':'умеренный климат',tags=[`<span class="tag">${climate}</span>`,`<span class="tag">аэропорт</span>`];if(r.closed)tags.push('<span class="tag warn">рейсы ограничены</span>');$('#regionTags').innerHTML=tags.join('')}
function select(i){if(state.selected!==i){state.selected=i;$$('.node').forEach(n=>n.classList.toggle('selected',+n.dataset.i===i))}updateRegionCard()}
function renderTree(force=false){const key=[state.started,state.tab,Math.floor(state.dna),Object.keys(state.owned).sort().join(',')].join('|');if(!force&&key===state.treeKey)return;state.treeKey=key;let box=$('#tree');box.innerHTML='';upgrades[state.tab].forEach(u=>{let locked=u.req&&!own(u.req),b=document.createElement('button');b.className='upgrade'+(own(u.id)?' owned':'')+(locked?' locked':'');b.disabled=!state.started||own(u.id)||locked||state.dna<u.cost;b.innerHTML=`<div class="upgrade-top"><b>${u.name}</b><span class="cost">${own(u.id)?'✓':u.cost+' ◈'}</span></div><p>${u.desc}</p>${u.req?`<div class="req">Требуется: ${Object.values(upgrades).flat().find(x=>x.id===u.req).name}</div>`:''}`;b.onclick=()=>buy(u);box.appendChild(b)})}
function buy(u){if(own(u.id)||state.dna<u.cost||(u.req&&!own(u.req)))return;state.dna-=u.cost;state.owned[u.id]=true;state.treeKey='';log(`Эволюция: ${u.name}`,'Эволюция');story('ЭВОЛЮЦИЯ',u.name,u.desc);render(true)}$$('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.treeKey='';$$('.tab').forEach(x=>x.classList.toggle('active',x===b));renderTree(true)});$$('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;$$('.speed').forEach(x=>x.classList.toggle('active',x===b))});
function spawnDNA(i,amount=1){let r=regions[i];if(!Number.isFinite(r.x))return;let g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','dna-pop');g.setAttribute('transform',`translate(${r.x+(Math.random()-.5)*18} ${r.y-18+(Math.random()-.5)*10})`);g.innerHTML='<circle class="orb" r="13"></circle><text y="1">◈</text>';g.onclick=()=>{state.dna+=amount;g.remove();state.treeKey='';log(`Собрано ДНК: +${amount} ◈`,'ДНК');render(true)};effects.appendChild(g)}
function addPlane(route,fromA=true){if(!route||route.type!=='air'||!Number.isFinite(regions[route.a].x))return;const max=mobile?4:8;if(planes.length>=max)return;let a=regions[fromA?route.a:route.b],b=regions[fromA?route.b:route.a],c=control(a,b,.09),g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','vehicle air');g.innerHTML='<path d="M-9,-1.1 L-2,-1.1 L3,-6.5 L5.5,-6.5 L3.7,-1.1 L9.5,0 L3.7,1.1 L5.5,6.5 L3,6.5 L-2,1.1 L-9,1.1 L-5.5,0 Z"></path>';effects.appendChild(g);planes.push({g,a,b,c,t:0,d:mobile?6200:5400});startAnimation()}
function startAnimation(){if(animating)return;animating=true;let last=performance.now();function frame(now){if(state.hidden){last=now;requestAnimationFrame(frame);return}let dt=Math.min(50,now-last);last=now;for(let i=planes.length-1;i>=0;i--){let p=planes[i];if(state.started&&!state.ended&&state.speed>0)p.t+=dt*state.speed/p.d;let t=Math.min(1,p.t),pt=qPoint(p.a,p.c,p.b,t),tg=qTangent(p.a,p.c,p.b,t),ang=Math.atan2(tg.y,tg.x)*180/Math.PI;p.g.setAttribute('transform',`translate(${pt.x.toFixed(1)} ${pt.y.toFixed(1)}) rotate(${ang.toFixed(1)})`);if(p.t>=1){p.g.remove();planes.splice(i,1)}}if(planes.length)requestAnimationFrame(frame);else animating=false}requestAnimationFrame(frame)}
function trafficTick(){if(state.hidden||!state.started||state.ended||state.speed===0)return;let usable=routes.filter(r=>r.type==='air'&&!regions[r.a].closed&&!regions[r.b].closed);if(!usable.length)return;addPlane(usable[Math.floor(Math.random()*usable.length)],Math.random()>.5)}
function maybeSpread(r,idx,s){let ratio=r.i/r.p;if(ratio<.0005)return;routes.filter(x=>x.a===idx||x.b===idx).forEach(route=>{let j=route.a===idx?route.b:route.a,to=regions[j];if(to.i>.001||to.d>to.p*.95)return;if((r.closed||to.closed)&&route.type==='air')return;let chance=.0017*(1+Math.min(7,ratio*80));if(route.type==='air')chance*=s.air;else chance*=1.35;if(Math.random()<chance){to.i=.002;spawnDNA(j,2);log(`${r.n} → ${to.n}: новая цепочка заражения`,'Распространение');story('НОВАЯ ВСПЫШКА',to.n,`Первые случаи обнаружены после перемещения из региона «${r.n}».`);if(route.type==='air')addPlane(route,route.a===idx)}})}function climateFactor(r,s){let f=1;if(r.c==='cold')f*=.58+Math.min(.4,s.cold);if(r.c==='hot')f*=.62+Math.min(.38,s.heat);return f}
function closureStep(share){if(share<.025||state.closures>=8)return;if(Math.random()<.0009*(1+share*6)){let c=regions.filter(r=>!r.closed&&r.i/r.p<.15&&r.w>=2);if(!c.length)return;let r=c[Math.floor(Math.random()*c.length)];r.closed=true;state.closures++;log(`${r.n} ограничивает международные рейсы`,'Ограничения');story('ОГРАНИЧЕНИЕ РЕЙСОВ',r.n,'Часть международных перелётов временно отменена.')}}
function randomStory(share){if(state.day-state.lastStory<18||Math.random()>.012)return;state.lastStory=state.day;let pool=share<.05?[['Городские слухи','В соцсетях обсуждают необычную вспышку.'],['Туристический сезон','Аэропорты фиксируют высокий пассажиропоток.'],['Медики насторожены','Клиники публикуют наблюдения о схожих симптомах.']]:share<.35?[['Экстренный саммит','Страны координируют меры и обмен данными.'],['Рынки реагируют','Транспорт и туризм сокращаются.'],['Исследовательская коалиция','Лаборатории объединяют ресурсы.']]:[['Глобальный кризис','Системы здравоохранения работают на пределе.'],['Массовые ограничения','Страны сокращают международные перелёты.'],['Последняя гонка','Исследователи ускоряют финальную фазу разработки лекарства.']];let x=pool[Math.floor(Math.random()*pool.length)];log(x[0]+': '+x[1],'Новости');story('МИРОВЫЕ НОВОСТИ',x[0],x[1])}
function cureStep(s,share){if(!state.detected)return;let research=(.0017+s.sev*.0032+share*.006)*(1+regions.filter(r=>r.w>=4&&r.i>0).length*.035)*(1-s.stealth)*(1-s.cureRes);state.cure=Math.min(100,state.cure+Math.max(.0004,research));[[25,'25%','Международная программа переходит к активной фазе.','c25'],[50,'50%','Половина работы над лекарством завершена.','c50'],[75,'75%','До завершения проекта остаётся немного времени.','c75'],[100,'100%','Начинается массовое применение лекарства.','c100']].forEach(x=>{if(state.cure>=x[0]&&!state[x[3]]){state[x[3]]=true;log(`Исследование лекарства: ${x[1]}`,'Лекарство');story('ИССЛЕДОВАНИЕ',`Лекарство: ${x[1]}`,x[2])}})}
function step(){if(state.hidden||!state.started||state.ended||state.speed===0)return;for(let n=0;n<state.speed;n++){state.day+=mobile?.5:.42;let s=stats(),newCases=0;regions.forEach((r,idx)=>{if(r.i<=0)return;let healthy=Math.max(0,r.p-r.i-r.d),growth=Math.min(healthy,r.i*.052*s.inf*climateFactor(r,s)*(healthy/r.p));if(state.cure>=100)growth-=r.i*(.10+.03*r.w);growth=Math.max(-r.i,growth);r.i+=growth;newCases+=Math.max(0,growth);let deaths=Math.min(r.i,r.i*s.let*(.55+.45*Math.min(1,r.i/r.p*3)));r.i-=deaths;r.d+=deaths;maybeSpread(r,idx,s)});let inf=total('i'),dead=total('d'),share=inf/WORLD;state.dna+=Math.min(.15,newCases*.0012);if(state.day-state.lastAutoDNA>11&&inf>.02){state.lastAutoDNA=state.day;let c=regions.filter(r=>r.i>.001);if(c.length)spawnDNA(c[Math.floor(Math.random()*c.length)].id,1)}if(!state.detected&&(inf>.7||s.sev>.18)){state.detected=true;log('Международные службы официально признают новую угрозу','Открытие');story('УГРОЗА ОБНАРУЖЕНА',state.name,'Начинается международное исследование лекарства.')}closureStep(share);randomStory(share);cureStep(s,share);let affected=inf+dead;if(affected/WORLD>=.99||dead/WORLD>.995){end(true);break}if(state.cure>=100&&inf<.002){end(false);break}}render()}
function render(force=false){let inf=total('i'),dead=total('d'),healthy=Math.max(0,WORLD-inf-dead),s=stats();$('#healthy').textContent=fmt(healthy);$('#infected').textContent=fmt(inf);$('#dead').textContent=fmt(dead);$('#dna').textContent=Math.floor(state.dna)+' ◈';$('#day').textContent='День '+Math.floor(state.day);$('#cureText').textContent=Math.floor(state.cure)+'%';$('#cureBar').style.width=state.cure+'%';$('#infectBar').style.width=Math.min(100,(s.inf-1)*110+18)+'%';$('#severityBar').style.width=Math.min(100,s.sev*150+5)+'%';$('#lethalBar').style.width=Math.min(100,s.let*9000+4)+'%';updateRegionCard();$$('.node').forEach(n=>{let r=regions[+n.dataset.i],ratio=(r.i+r.d)/r.p;n.classList.toggle('infected',r.i>.001);n.classList.toggle('deadly',r.d>r.i&&r.d>r.p*.08);n.classList.toggle('closed',r.closed);n.querySelector('.fill').setAttribute('r',String(2.8+Math.min(7.2,ratio*11)))});$$('.route').forEach(l=>{let r=routes[+l.dataset.route],a=regions[r.a],b=regions[r.b];l.classList.toggle('active',a.i>.01||b.i>.01);l.classList.toggle('closed',(a.closed||b.closed)&&r.type==='air')});renderTree(force)}
function end(win){state.ended=true;state.speed=0;let inf=total('i'),dead=total('d');$('#resultOverlay').classList.remove('hidden');$('#resultKicker').textContent=win?'ГЛОБАЛЬНЫЙ ОХВАТ':'ВСПЫШКА ОСТАНОВЛЕНА';$('#resultTitle').textContent=win?'ПОБЕДА':'ПОРАЖЕНИЕ';$('#resultText').textContent=win?`${state.name} охватил практически весь мир раньше, чем программа лекарства смогла остановить распространение.`:`Лекарство завершено, а последние активные очаги ${state.name} исчезли.`;$('#resultScore').textContent=`День ${Math.floor(state.day)} • заражено ${fmt(inf)} • погибло ${fmt(dead)} • эволюций ${Object.keys(state.owned).length}`}
regions.forEach((r,i)=>$('#startSelect').insertAdjacentHTML('beforeend',`<option value="${i}">${r.n}</option>`));$('#startSelect').value='3';$('#startBtn').onclick=()=>{let idx=+$('#startSelect').value;state.name=($('#nameInput').value||'ZERO-01').trim().slice(0,22)||'ZERO-01';$('#pathogenName').textContent=state.name;regions[idx].i=.02;state.started=true;state.selected=null;state.treeKey='';$('#startOverlay').classList.add('hidden');select(idx);spawnDNA(idx,2);log(`${state.name}: первые случаи зарегистрированы — ${regions[idx].n}`,'Начало');story('НУЛЕВОЙ ДЕНЬ',regions[idx].n,`Образец «${state.name}» начал распространяться.`);render(true)};$('#historyBtn').onclick=()=>{renderHistory();$('#historyOverlay').classList.remove('hidden')};$('#closeHistory').onclick=()=>$('#historyOverlay').classList.add('hidden');$('#historyOverlay').onclick=e=>{if(e.target===$('#historyOverlay'))$('#historyOverlay').classList.add('hidden')};document.addEventListener('visibilitychange',()=>state.hidden=document.hidden);
positionGameLayers();buildMap();render(true);setInterval(step,mobile?760:620);setInterval(trafficTick,mobile?2400:1750);
})();