(()=>{'use strict';
const svg=document.querySelector('#map'),nodesRoot=document.querySelector('#nodes'),geo=document.querySelector('#geo');if(!svg||!nodesRoot)return;const NS='http://www.w3.org/2000/svg',mobile=matchMedia('(max-width:640px)').matches;
let defs=svg.querySelector('#infectionDefs');if(!defs){defs=document.createElementNS(NS,'defs');defs.id='infectionDefs';defs.innerHTML='<radialGradient id="infectionGlow"><stop offset="0%" stop-color="#ff6b52" stop-opacity=".55"/><stop offset="38%" stop-color="#ff4f3c" stop-opacity=".28"/><stop offset="100%" stop-color="#ff3d2e" stop-opacity="0"/></radialGradient>';svg.insertBefore(defs,svg.firstChild)}
let layer=svg.querySelector('.infection-layer');if(!layer){layer=document.createElementNS(NS,'g');layer.setAttribute('class','infection-layer');const routes=document.querySelector('#routes');svg.insertBefore(layer,routes||nodesRoot)}
let regionFx=[],countryMap=[],lastInfected=new Set(),timer=0,dirty=true,geoDirty=true;
function parseXY(node){const m=(node.getAttribute('transform')||'').match(/translate\(([-\d.]+)[ ,]([-\d.]+)\)/);return m?[+m[1],+m[2]]:[0,0]}
function seeded(seed){let s=(seed+1)*9301+49297;return()=>((s=(s*233280+49297)%233280)/233280)}
function pathFor(seed,x,y,a,len,bend){const r=seeded(seed),ang=a+(r()-.5)*.5,l1=len*(.42+r()*.18),l2=len*(.28+r()*.26),x1=x+Math.cos(ang)*l1,y1=y+Math.sin(ang)*l1,x2=x1+Math.cos(ang+bend+(r()-.5)*.35)*l2,y2=y1+Math.sin(ang+bend+(r()-.5)*.35)*l2;return`M ${x.toFixed(1)} ${y.toFixed(1)} Q ${(x1+(r()-.5)*8).toFixed(1)} ${(y1+(r()-.5)*8).toFixed(1)} ${x2.toFixed(1)} ${y2.toFixed(1)}`}
function build(){layer.innerHTML='';regionFx=[];nodesRoot.querySelectorAll('.node').forEach((node,i)=>{const [x,y]=parseXY(node),g=document.createElementNS(NS,'g');g.setAttribute('class','infection-region');g.dataset.i=i;const halo=document.createElementNS(NS,'circle');halo.setAttribute('class','infection-halo');halo.setAttribute('cx',x);halo.setAttribute('cy',y);halo.setAttribute('r','1');g.appendChild(halo);const core=document.createElementNS(NS,'circle');core.setAttribute('class','infection-core');core.setAttribute('cx',x);core.setAttribute('cy',y);core.setAttribute('r','4');g.appendChild(core);const veins=[];for(let v=0;v<7;v++){const p=document.createElementNS(NS,'path'),ang=Math.PI*2/7*v;p.setAttribute('class','infection-vein'+(v%3===0?' inner':''));p.setAttribute('pathLength','1');p.setAttribute('d',pathFor(i*31+v,x,y,ang,32+(v%3)*7,v%2?.22:-.22));g.appendChild(p);veins.push(p)}const hotspots=[];for(let h=0;h<3;h++){const rr=seeded(i*17+h),ang=rr()*Math.PI*2,dist=14+rr()*28,c=document.createElementNS(NS,'circle');c.setAttribute('class','infection-hotspot h'+(h+1));c.setAttribute('cx',(x+Math.cos(ang)*dist).toFixed(1));c.setAttribute('cy',(y+Math.sin(ang)*dist).toFixed(1));c.setAttribute('r',(2.2+rr()*2.1).toFixed(1));g.appendChild(c);hotspots.push(c)}layer.appendChild(g);regionFx.push({g,halo,core,veins,hotspots,node,x,y,key:''})});geoDirty=true;dirty=true}
function mapCountries(){const countries=[...geo?.querySelectorAll('.country')||[]];countryMap=[];if(!countries.length)return;const boxes=countries.map(p=>{try{const b=p.getBBox();return{p,cx:b.x+b.width/2,cy:b.y+b.height/2}}catch{return{p,cx:1e9,cy:1e9}}});regionFx.forEach((fx,i)=>{const scored=boxes.map(o=>{let d=(o.cx-fx.x)**2+(o.cy-fx.y)**2;try{if(o.p.isPointInFill&&o.p.isPointInFill(new DOMPoint(fx.x,fx.y)))d=-1e5}catch{}return{p:o.p,d}}).sort((a,b)=>a.d-b.d);const take=[6,7,8,9,10,12,18].includes(i)?4:2;countryMap[i]=scored.slice(0,take).map(x=>x.p)});geoDirty=false;dirty=true}
function intensityFromNode(node){if(!node.classList.contains('infected')&&!node.classList.contains('deadly'))return 0;const r=parseFloat(node.querySelector('circle.fill')?.getAttribute('r')||'2.8');return Math.max(.06,Math.min(1,(r-2.8)/7.2))}
function mix(a,b,t){return a.map((v,i)=>Math.round(v+(b[i]-v)*t))}function rgb(c){return`rgb(${c[0]},${c[1]},${c[2]})`}
function applyFx(fx,i){const p=intensityFromNode(fx.node),dead=fx.node.classList.contains('deadly'),key=`${Math.round(p*100)}:${dead?1:0}`;if(key===fx.key)return;fx.key=key;fx.g.classList.toggle('live',p>0);fx.g.classList.toggle('critical',p>.62);fx.g.classList.toggle('dead-zone',dead);fx.halo.setAttribute('r',(10+p*54).toFixed(1));fx.halo.style.opacity=p?String(.14+p*.48):'0';fx.core.style.opacity=p?String(.22+p*.72):'0';fx.core.setAttribute('r',(3.2+p*4.8).toFixed(1));fx.veins.forEach((v,j)=>{const local=Math.max(0,Math.min(1,(p-j/9)*2.25));v.style.opacity=local?String(.16+local*.68):'0';v.style.strokeDashoffset=String(1-local);v.style.strokeWidth=String(.55+local*1.15)});fx.hotspots.forEach((h,j)=>h.style.opacity=String(Math.max(0,(p-.12-j*.09)*1.5)));const now=p>0;if(now&&!lastInfected.has(i))arrival(fx);if(now)lastInfected.add(i);(countryMap[i]||[]).forEach((c,k)=>{const q=p*Math.max(.18,1-k*.18);if(q>0){const col=mix([37,72,50],dead?[70,72,69]:[103,45,34],Math.min(.88,q*.82));c.classList.add('infection-tint');c.style.fill=rgb(col);c.style.stroke=dead?'#bcc1bd':q>.55?'#e58b76':'#adc1b3';c.style.opacity=String(.9+q*.1)}else if(c.classList.contains('infection-tint')){c.style.removeProperty('fill');c.style.removeProperty('stroke');c.style.removeProperty('opacity');c.classList.remove('infection-tint')}})}
function flush(){timer=0;if(document.hidden)return;if(geoDirty)mapCountries();if(!dirty)return;dirty=false;regionFx.forEach(applyFx)}
function schedule(){dirty=true;if(timer||document.hidden)return;timer=setTimeout(flush,mobile?220:140)}
function arrival(fx){const group=document.createElementNS(NS,'g');for(let k=0;k<2;k++){const c=document.createElementNS(NS,'circle');c.setAttribute('class','infection-arrival'+(k?' arrival2':''));c.setAttribute('cx',fx.x);c.setAttribute('cy',fx.y);c.setAttribute('r','6');group.appendChild(c)}for(let s=0;s<(mobile?5:9);s++){const r=seeded(fx.x+fx.y+s),a=r()*Math.PI*2,d=18+r()*26,c=document.createElementNS(NS,'circle');c.setAttribute('class','infection-spark');c.setAttribute('cx',fx.x);c.setAttribute('cy',fx.y);c.setAttribute('r',(1.3+r()*1.5).toFixed(1));c.style.setProperty('--sx',(Math.cos(a)*d).toFixed(1)+'px');c.style.setProperty('--sy',(Math.sin(a)*d).toFixed(1)+'px');group.appendChild(c)}layer.appendChild(group);setTimeout(()=>group.remove(),1200)}
const nodeObserver=new MutationObserver(m=>{let rebuild=false;for(const x of m){if(x.type==='childList'){rebuild=true;break}}if(rebuild)build();schedule()});nodeObserver.observe(nodesRoot,{childList:true,subtree:true,attributes:true,attributeFilter:['class','r','transform']});if(geo)new MutationObserver(()=>{geoDirty=true;schedule()}).observe(geo,{childList:true});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){dirty=true;schedule()}});build();schedule();
})();