(()=>{'use strict';
const mobile=matchMedia('(max-width:640px)').matches;if(mobile)return;
const svg=document.querySelector('#map'),map=document.querySelector('.map-wrap'),nodes=document.querySelector('#nodes');if(!svg||!map||!nodes)return;const NS='http://www.w3.org/2000/svg';
const cities=[['Нью-Йорк',-74,40.71,1],['Лос-Анджелес',-118.24,34.05,1],['Мехико',-99.13,19.43,2],['Сан-Паулу',-46.63,-23.55,3],['Буэнос-Айрес',-58.38,-34.6,4],['Лондон',-.13,51.51,5],['Париж',2.35,48.86,6],['Берлин',13.4,52.52,6],['Москва',37.62,55.75,12],['Каир',31.24,30.04,8],['Лагос',3.38,6.52,9],['Йоханнесбург',28.05,-26.2,11],['Дубай',55.27,25.2,13],['Дели',77.1,28.7,14],['Мумбаи',72.88,19.08,14],['Пекин',116.41,39.9,16],['Шанхай',121.47,31.23,16],['Токио',139.69,35.68,17],['Сеул',126.98,37.57,18],['Бангкок',100.5,13.75,18],['Сингапур',103.82,1.35,18],['Джакарта',106.85,-6.21,19],['Сидней',151.21,-33.87,20]];
let defs=svg.querySelector('#nightLightDefs');if(!defs){defs=document.createElementNS(NS,'defs');defs.id='nightLightDefs';defs.innerHTML='<radialGradient id="nightCityGlow"><stop offset="0" stop-color="#fff7c8" stop-opacity=".72"/><stop offset="30%" stop-color="#ffd978" stop-opacity=".34"/><stop offset="100%" stop-color="#ffc95f" stop-opacity="0"/></radialGradient><radialGradient id="nightCityWarn"><stop offset="0" stop-color="#ffd39a" stop-opacity=".65"/><stop offset="100%" stop-color="#ff6a4f" stop-opacity="0"/></radialGradient>';svg.insertBefore(defs,svg.firstChild)}
let layer=svg.querySelector('#nightLights');if(layer)layer.remove();layer=document.createElementNS(NS,'g');layer.id='nightLights';layer.setAttribute('class','night-lights-layer');svg.insertBefore(layer,nodes);
const projection=window.d3?d3.geoEquirectangular().scale(151).translate([500,260]).clipExtent([[18,20],[982,500]]):null,fallback=(lon,lat)=>[500+lon*2.55,260-lat*2.5];
const groups=[];cities.forEach((c,i)=>{const[name,lon,lat,region]=c,p=projection?projection([lon,lat]):fallback(lon,lat);if(!p)return;const g=document.createElementNS(NS,'g');g.classList.add('city-cluster');g.dataset.region=region;g.setAttribute('transform',`translate(${p[0].toFixed(1)} ${p[1].toFixed(1)})`);const halo=document.createElementNS(NS,'circle');halo.classList.add('city-halo');halo.setAttribute('r','10');g.appendChild(halo);for(let k=0;k<3;k++){const dot=document.createElementNS(NS,'circle');dot.classList.add('city-light');if(k===0)dot.classList.add('core');dot.setAttribute('cx',String(k===1?3.2:k===2?-3.4:0));dot.setAttribute('cy',String(k===1?-1.4:k===2?1.8:0));dot.setAttribute('r',String(k===0?1.55:.85));g.appendChild(dot)}layer.appendChild(g);groups.push({g,region,key:''})});
let timer=0;function readState(node){if(!node)return{p:0,dead:false};const r=parseFloat(node.querySelector('circle.fill')?.getAttribute('r')||'2.8'),infected=node.classList.contains('infected'),dead=node.classList.contains('deadly');let p=Math.max(0,Math.min(1,(r-2.8)/7.2));if(infected&&p<.08)p=.08;return{p,dead}}
function update(){timer=0;if(document.hidden)return;for(const item of groups){const node=nodes.querySelector(`.node[data-i="${item.region}"]`),s=readState(node),key=`${Math.round(s.p*10)}:${s.dead?1:0}`;if(key===item.key)continue;item.key=key;item.g.classList.toggle('infected',s.p>.06&&!s.dead);item.g.classList.toggle('blackout',s.dead);item.g.style.opacity=(s.dead?.05:Math.max(.38,1-s.p*.48)).toFixed(2)}}
function schedule(){if(timer||document.hidden)return;timer=setTimeout(update,180)}
new MutationObserver(schedule).observe(nodes,{subtree:true,attributes:true,childList:true,attributeFilter:['class','r']});document.addEventListener('visibilitychange',()=>{if(!document.hidden){groups.forEach(x=>x.key='');schedule()}});update();
})();