(()=>{'use strict';
const $=s=>document.querySelector(s),SAVE='qc_cases_v1';
let C=load(),shift={total:0,processed:0,triggerAt:2,triggered:false},pending=null,toastTimer=null;
function load(){try{return Object.assign({loyalty:100,shadow:0,cases:0,bribes:0,exceptions:0},JSON.parse(localStorage.getItem(SAVE)||'{}'))}catch(e){return{loyalty:100,shadow:0,cases:0,bribes:0,exceptions:0}}}
function save(){C.loyalty=Math.max(0,Math.min(100,Math.round(C.loyalty)));C.shadow=Math.max(0,Math.round(C.shadow));localStorage.setItem(SAVE,JSON.stringify(C))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function inject(){const anchor=$('#missionBar')||$('.qc-bulletin');if(!anchor)return;const strip=document.createElement('div');strip.className='qc-ethics-strip';strip.innerHTML='<div class="loyal" id="caseLoyal"><small>СЛУЖЕБНАЯ ЛОЯЛЬНОСТЬ</small><b id="caseLoyalValue">100</b></div><div class="cash"><small>СЕРАЯ КАССА</small><b id="caseCashValue">0 ¤</b></div>';anchor.insertAdjacentElement('afterend',strip);
 const overlay=document.createElement('div');overlay.className='qc-case-overlay';overlay.id='caseOverlay';overlay.innerHTML='<div class="qc-case-card"><div class="qc-case-kicker" id="caseKicker">ОСОБОЕ ДЕЛО</div><h3 id="caseTitle">Ситуация</h3><p id="caseText"></p><p class="qc-case-quote" id="caseQuote"></p><div class="qc-case-actions" id="caseActions"></div><div class="qc-case-note">Решение здесь не заменяет печать. После разговора вы всё равно принимаете официальное решение по документам.</div></div>';document.body.appendChild(overlay);
 const toast=document.createElement('div');toast.className='qc-case-toast';toast.id='caseToast';toast.innerHTML='<b id="caseToastTitle"></b><span id="caseToastText"></span>';document.body.appendChild(toast);render();observe()}
function render(){const el=$('#caseLoyal'),v=$('#caseLoyalValue'),cash=$('#caseCashValue');if(!el||!v||!cash)return;v.textContent=C.loyalty;cash.textContent=C.shadow+' ¤';el.classList.remove('good','warn','bad');el.classList.add(C.loyalty>=75?'good':C.loyalty>=45?'warn':'bad')}
function toast(title,text){const el=$('#caseToast');if(!el)return;$('#caseToastTitle').textContent=title;$('#caseToastText').textContent=text||'';el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2700)}
function current(){return{name:$('#personName')?.textContent.trim()||'',nation:$('#passportNation')?.textContent.trim()||'',purpose:$('#purpose')?.textContent.trim()||'',route:$('#route')?.textContent.trim()||'',passName:$('#passportName')?.textContent.trim()||'',healthName:$('#healthName')?.textContent.trim()||'',permitName:$('#permitName')?.textContent.trim()||'',expiry:$('#passportExpiry')?.textContent.trim()||'',test:$('#testResult')?.textContent.trim()||'',age:parseInt($('#testAge')?.textContent)||0,temp:parseFloat(($('#temperature')?.textContent||'').replace(',','.'))||0}}
function obviouslyInvalid(p){const year=parseInt((p.expiry.match(/(20\d{2})/)||[])[1])||9999;return(p.healthName&&p.healthName!==p.passName)||(p.permitName&&p.permitName!=='НЕТ ДОКУМЕНТА'&&p.permitName!==p.passName)||year<2026||(p.test&&p.test!=='ОТРИЦАТЕЛЬНЫЙ')||p.age>72||p.temp>37.7}
function addChip(text){const s=$('#caseStrip');if(!s)return;const chip=document.createElement('span');chip.className='case-chip qc-case-chip';chip.textContent=text;s.appendChild(chip)}
function showCase(type,p){shift.triggered=true;const ov=$('#caseOverlay'),actions=$('#caseActions');if(!ov||!actions)return;let title='',text='',quote='',buttons=[];if(type==='bribe'){const amount=25+Math.floor(Math.random()*4)*10;title='Предложение под стеклом';text='В документах есть повод для отказа. Пассажир понимает это раньше, чем вы ставите печать.';quote=`«${amount}¤ наличными. Вы пропускаете меня — и этой ошибки в бумагах никогда не существовало.»`;buttons=[['ВЗЯТЬ '+amount+'¤','tempt',()=>choose({type:'bribe',mode:'accept',amount,name:p.name})],['ДОЛОЖИТЬ О ПОПЫТКЕ','protocol',()=>choose({type:'bribe',mode:'report',amount,name:p.name})]]}else if(type==='human'){title='Просьба об исключении';text=p.purpose==='лечение'?'Документы не проходят протокол, но человек утверждает, что опоздание сорвёт срочную медицинскую помощь.':'Документы не проходят протокол. Пассажир просит сделать исключение ради семьи.';quote=p.purpose==='лечение'?'«Если я сегодня не попаду в медицинский сектор, следующий приём будет только через месяц. Пожалуйста.»':'«Там моя семья. Я понимаю правила, но мне больше не к кому идти.»';buttons=[['ОБЕЩАТЬ ПОМОЧЬ','human',()=>choose({type:'human',mode:'help',name:p.name})],['ТОЛЬКО ПО ПРОТОКОЛУ','protocol',()=>choose({type:'human',mode:'protocol',name:p.name})]]}else{title='Звонок сверху';text='На служебную линию поступает распоряжение ускорить именно этого пассажира. Формально отменять проверки никто не приказал.';quote='«Очередь стоит. Не тратьте на него время. Решение — быстро, без лишних процедур.»';buttons=[['ВЫПОЛНИТЬ РАСПОРЯЖЕНИЕ','tempt',()=>choose({type:'fast',mode:'agree',name:p.name,extras:0})],['РАБОТАТЬ КАК ОБЫЧНО','protocol',()=>choose({type:'fast',mode:'normal',name:p.name,extras:0})]]}
 $('#caseKicker').textContent=type==='bribe'?'НЕЗАРЕГИСТРИРОВАННЫЙ КОНТАКТ':type==='human'?'ГУМАНИТАРНОЕ ОБРАЩЕНИЕ':'СЛУЖЕБНЫЙ КАНАЛ';$('#caseTitle').textContent=title;$('#caseText').textContent=text;$('#caseQuote').textContent=quote;actions.innerHTML='';buttons.forEach(([label,cls,fn])=>{const b=document.createElement('button');b.className=cls;b.textContent=label;b.onclick=fn;actions.appendChild(b)});ov.classList.add('show');if(navigator.vibrate)navigator.vibrate([12,40,12])}
function choose(data){pending=data;$('#caseOverlay')?.classList.remove('show');addChip(data.type==='bribe'?(data.mode==='accept'?'СДЕЛКА':'ДОЛОЖЕНО'):data.type==='human'?(data.mode==='help'?'ОБЕЩАНИЕ':'ПРОТОКОЛ'):(data.mode==='agree'?'УСКОРИТЬ':'ШТАТНО'));toast('РЕШЕНИЕ ЗАФИКСИРОВАНО','Теперь поставьте официальную печать.')}
function resolve(approve){if(!pending)return;const name=$('#personName')?.textContent.trim()||'';if(name!==pending.name){pending=null;return}let title='ОСОБОЕ ДЕЛО',text='';if(pending.type==='bribe'){if(pending.mode==='accept'){if(approve){C.shadow+=pending.amount;C.loyalty-=12;C.bribes++;title='СДЕЛКА СОСТОЯЛАСЬ';text=`+${pending.amount}¤ в серую кассу. Внутренняя безопасность это не одобрит.`}else{C.loyalty-=2;title='СДЕЛКА СОРВАНА';text='Вы взяли предложение к рассмотрению, но в итоге отказали пассажиру.'}}else{if(!approve){C.loyalty+=4;title='ПОПЫТКА ВЗЯТКИ ЗАФИКСИРОВАНА';text='Служебная лояльность повышена.'}else{C.loyalty-=7;title='ДОКЛАД ПРОИГНОРИРОВАН';text='Вы сообщили о взятке, а затем всё равно пропустили пассажира.'}}}else if(pending.type==='human'){if(pending.mode==='help'){if(approve){C.loyalty-=3;C.exceptions++;title='ИСКЛЮЧЕНИЕ СДЕЛАНО';text='Человечески понятно. Формально — отклонение от протокола.'}else{C.loyalty-=4;title='ОБЕЩАНИЕ НАРУШЕНО';text='Вы пообещали помочь, но поставили отказ.'}}else{if(!approve){C.loyalty+=2;title='ПРОТОКОЛ СОБЛЮДЁН';text='Личное обстоятельство не изменило официальное решение.'}else{C.loyalty-=5;title='НЕЗАЯВЛЕННОЕ ИСКЛЮЧЕНИЕ';text='Вы заявили, что будете следовать протоколу, но пропустили пассажира.'}}}else if(pending.type==='fast'){if(pending.mode==='agree'){if((pending.extras||0)===0){C.loyalty+=2;title='РАСПОРЯЖЕНИЕ ВЫПОЛНЕНО';text='Дело закрыто без дополнительных процедур.'}else{C.loyalty-=2;title='РАСПОРЯЖЕНИЕ СОРВАНО';text='Вы согласились ускорить пассажира, но всё равно затянули проверку.'}}else{C.loyalty+=1;title='НЕЗАВИСИМАЯ ПРОВЕРКА';text='Вы не позволили давлению изменить процедуру.'}}C.cases++;save();render();toast(title,text);pending=null}
function maybeTrigger(){if(shift.triggered||!shift.total||$('#startOverlay')&&!$('#startOverlay').classList.contains('hidden'))return;const p=current();if(!p.name||p.name==='—')return;if(shift.processed<shift.triggerAt)return;const invalid=obviouslyInvalid(p);if(invalid){const human=(p.purpose==='лечение'||p.purpose==='семья')&&Math.random()<.58;showCase(human?'human':'bribe',p)}else if(shift.processed>=Math.max(5,shift.triggerAt+2)){showCase('fast',p)}}
function newShift(total){shift={total,processed:0,triggerAt:1+Math.floor(Math.random()*3),triggered:false};pending=null}
function summary(){const paper=$('.qc-modal.newspaper');if(!paper)return;let box=paper.querySelector('.qc-case-summary');if(!box){box=document.createElement('div');box.className='qc-case-summary';const actions=paper.querySelector('.qc-shift-actions');paper.insertBefore(box,actions||null)}box.classList.toggle('danger',C.loyalty<45||C.shadow>=100);let tail=C.loyalty<45?'Внутренняя безопасность отметила отклонения от протокола.':C.shadow>=100?'Объём неучтённых средств уже выглядит подозрительно.':'Серьёзных вопросов службы внутреннего контроля нет.';box.innerHTML=`<b>Служебная этика:</b> лояльность ${C.loyalty}/100 • серая касса ${C.shadow}¤.<br>${esc(tail)}`}
function observe(){const processed=$('#processedNow');if(processed)new MutationObserver(()=>{const a=processed.textContent.split('/').map(x=>parseInt(x)||0);if(a[1]&&a[1]!==shift.total)newShift(a[1]);shift.processed=a[0]}).observe(processed,{childList:true,characterData:true,subtree:true});const person=$('#personName');if(person)new MutationObserver(()=>setTimeout(maybeTrigger,90)).observe(person,{childList:true,characterData:true,subtree:true});
 $('#approveBtn')?.addEventListener('click',()=>resolve(true));$('#denyBtn')?.addEventListener('click',()=>resolve(false));$('#inspectBtn')?.addEventListener('click',()=>{if(pending?.type==='fast')pending.extras=(pending.extras||0)+1});$('#questionBtn')?.addEventListener('click',()=>{if(pending?.type==='fast')pending.extras=(pending.extras||0)+1});
 const shiftOv=$('#shiftOverlay');if(shiftOv)new MutationObserver(()=>{if(!shiftOv.classList.contains('hidden'))setTimeout(summary,60)}).observe(shiftOv,{attributes:true,attributeFilter:['class']});}
function init(){inject()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();