(()=>{'use strict';
const $=s=>document.querySelector(s);
const nameEl=$('#personName');
if(!nameEl)return;
const FEMALE=new Set(['Мира','Елена','София','Ника','Дана','Алиса','Лея','Эмма']);
const eyes=['КАРИЕ','СЕРЫЕ','ЗЕЛЁНЫЕ','ГОЛУБЫЕ'];
const labs=['ЦЕНТР-07','Q-MED NORTH','АРДЕН LAB','BIOCHECK','VESP-LAB'];
const methods=['RT-PCR','PCR-Q','LAMP-Q'];
const dest={работа:'ПРОМЗОНА-4',транзит:'ТРАНЗИТНЫЙ КОРИДОР',семья:'ЖИЛОЙ СЕКТОР-2',лечение:'МЕДСЕКТОР-1',учёба:'АКАДЕМИЧЕСКИЙ КВАРТАЛ',дипмиссия:'АДМИНИСТРАТИВНЫЙ СЕКТОР'};
const authority={Арден:'ARDEN CIVIL AUTH.',Норда:'NORDA BORDER OFFICE',Веспер:'VESPER STATE BUREAU',Лира:'LYRA MIGRATION DEPT.',Кармин:'KARMIN ENTRY SERVICE',Остара:'OSTARA CIVIL REG.'};
function text(sel){return($(sel)?.textContent||'').trim()}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function two(n){return String(n).padStart(2,'0')}
function val(seed,min,max,shift=0){return min+((seed>>>shift)%(max-min+1))}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function birth(seed,name){const first=(name||'').split(' ')[0],age=val(seed,20,61,3),year=2026-age,month=val(seed,1,12,9),day=val(seed,1,28,14);return{date:`${two(day)}.${two(month)}.${year}`,sex:FEMALE.has(first)?'Ж':'М',height:val(seed,158,194,18)+' СМ',eyes:eyes[val(seed,0,eyes.length-1,22)]}}
function serial(seed,prefix='Q'){const n=seed>>>0;return `${prefix}${(n%999999).toString().padStart(6,'0')}`}
function ensureStructures(){
 const passport=$('.qc-document.passport'),health=$('.qc-document.health'),permit=$('.qc-document.permit');
 if(passport&&!passport.querySelector('.qc-doc-fill')) passport.insertAdjacentHTML('beforeend',`<div class="qc-doc-fill qc-passport-fill"><div class="qc-doc-grid"><div class="qc-doc-cell"><small>Дата рождения</small><b data-doc="dob">—</b></div><div class="qc-doc-cell"><small>Пол</small><b data-doc="sex">—</b></div><div class="qc-doc-cell"><small>Рост</small><b data-doc="height">—</b></div><div class="qc-doc-cell"><small>Глаза</small><b data-doc="eyes">—</b></div><div class="qc-doc-cell"><small>Дата выдачи</small><b data-doc="issued">—</b></div><div class="qc-doc-cell"><small>Орган выдачи</small><b data-doc="authority">—</b></div><div class="qc-doc-cell"><small>Серия BIO-ID</small><b data-doc="bioid">—</b></div><div class="qc-doc-cell"><small>Класс документа</small><b>P / CIV</b></div></div><div class="qc-doc-security"><div class="qc-security-seal">CIVIL<br>REGISTRY</div><div><div class="qc-signature" data-doc="signature">—</div><small class="qc-signature-label">подпись владельца</small></div><div><div class="qc-barcode" data-doc="passportBarcode" data-code="000000"></div><small class="qc-signature-label">машинный код</small></div></div><div class="qc-mrz" data-doc="mrz">P&lt;STATE&lt;&lt;NAME&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;<br>000000&lt;0STATE0000000&lt;0000000&lt;&lt;&lt;&lt;</div></div>`);
 if(health&&!health.querySelector('.qc-doc-fill')) health.insertAdjacentHTML('beforeend',`<div class="qc-doc-fill qc-health-fill"><div class="qc-doc-grid"><div class="qc-doc-cell"><small>Метод</small><b data-doc="method">—</b></div><div class="qc-doc-cell"><small>Лаборатория</small><b data-doc="lab">—</b></div><div class="qc-doc-cell"><small>Код образца</small><b data-doc="sample">—</b></div><div class="qc-doc-cell"><small>Взятие образца</small><b data-doc="sampleTime">—</b></div><div class="qc-doc-cell"><small>Симптомы</small><b data-doc="symptoms">НЕ ЗАЯВЛЕНЫ</b></div><div class="qc-doc-cell"><small>Категория риска</small><b data-doc="risk">—</b></div><div class="qc-doc-cell"><small>Контроль</small><b>Q-17 / AUTO</b></div><div class="qc-doc-cell"><small>Статус записи</small><b>СИНХРОНИЗИРОВАНО</b></div></div><div class="qc-med-band"><div class="qc-med-check">ИДЕНТИФИКАЦИЯ<b>✓ VERIFIED</b></div><div class="qc-med-check">ОБРАЗЕЦ<b>✓ SEALED</b></div><div class="qc-med-check">ТЕРМОКОНТРОЛЬ<b data-doc="thermo">✓ NORMAL</b></div></div><div class="qc-doc-security"><div class="qc-security-seal">Q-MED<br>LAB</div><div><div class="qc-signature">Q-Med / 07</div><small class="qc-signature-label">электронная подпись лаборатории</small></div><div><div class="qc-barcode" data-doc="healthBarcode" data-code="000000"></div><small class="qc-signature-label">sample trace</small></div></div></div>`);
 if(permit&&!permit.querySelector('.qc-doc-fill')) permit.insertAdjacentHTML('beforeend',`<div class="qc-doc-fill qc-permit-fill"><div class="qc-doc-grid"><div class="qc-doc-cell"><small>№ разрешения</small><b data-doc="permitNo">—</b></div><div class="qc-doc-cell"><small>Орган выдачи</small><b data-doc="permitAuthority">—</b></div><div class="qc-doc-cell"><small>Пункт назначения</small><b data-doc="destination">—</b></div><div class="qc-doc-cell"><small>Уровень допуска</small><b data-doc="clearance">—</b></div><div class="qc-doc-cell"><small>Канал въезда</small><b>GATE 07 / B</b></div><div class="qc-doc-cell"><small>Реестр</small><b data-doc="registry">—</b></div><div class="qc-doc-cell"><small>Проверка маршрута</small><b data-doc="routeCheck">—</b></div><div class="qc-doc-cell"><small>Статус</small><b data-doc="permitStatus">—</b></div></div><div class="qc-permit-note"><b>Служебное ограничение</b><span data-doc="permitNote">Документ действует только для указанной цели, маршрута и срока пребывания.</span></div><div class="qc-doc-security"><div class="qc-security-seal">ENTRY<br>AUTH</div><div><div class="qc-signature">Sector 07</div><small class="qc-signature-label">подпись контролёра реестра</small></div><div><div class="qc-barcode" data-doc="permitBarcode" data-code="000000"></div><small class="qc-signature-label">registry trace</small></div></div></div>`);
}
function set(key,value){document.querySelectorAll(`[data-doc="${key}"]`).forEach(el=>{if(el.classList.contains('qc-barcode'))el.dataset.code=value;else el.innerHTML=esc(value).replace(/\n/g,'<br>')})}
function render(){ensureStructures();const name=text('#personName');if(!name||name==='—')return;const seed=hash(name+'|'+text('#passportNo')),person=birth(seed,name),nation=text('#passportNation'),purpose=text('#purpose'),expiry=text('#passportExpiry'),permitName=text('#permitName'),permitType=text('#permitType'),route=text('#route'),test=text('#testResult'),temp=parseFloat(text('#temperature').replace(',','.'))||0,testAge=parseInt(text('#testAge'))||0;
 const expYear=parseInt((expiry.match(/(20\d{2})/)||[])[1])||2028,issueYear=expYear-5,issueMonth=val(seed,1,12,6),issueDay=val(seed,1,28,12);
 set('dob',person.date);set('sex',person.sex);set('height',person.height);set('eyes',person.eyes);set('issued',`${two(issueDay)}.${two(issueMonth)}.${issueYear}`);set('authority',authority[nation]||'CENTRAL CIVIL REG.');set('bioid',serial(seed,'B'));set('signature',(name.split(' ')[0]||name).slice(0,12));set('passportBarcode',serial(seed,'P'));
 const safeName=name.toUpperCase().replace(/[^А-ЯA-Z]/g,'<').slice(0,18),safeNation=(nation||'STATE').toUpperCase().replace(/[^А-ЯA-Z]/g,'').slice(0,6),pass=text('#passportNo').replace(/[^A-ZА-Я0-9]/gi,'').slice(0,10);set('mrz',`P<${safeNation}<<${safeName}<<<<<<<<\n${pass}<${person.sex}${person.date.replace(/\./g,'').slice(0,6)}${String(expYear).slice(2)}1231<<<<<`);
 set('method',methods[val(seed,0,methods.length-1,7)]);set('lab',labs[val(seed,0,labs.length-1,11)]);set('sample',serial(seed^0x45a12,'S'));set('sampleTime',`T−${testAge||0} Ч`);const elevated=temp>37.4,badTest=test&&test!=='ОТРИЦАТЕЛЬНЫЙ';set('risk',badTest?'ВЫСОКИЙ':elevated?'ПОВЫШЕННЫЙ':'НИЗКИЙ');set('thermo',elevated?'! REVIEW':'✓ NORMAL');set('healthBarcode',serial(seed^0x9912,'M'));
 const missing=permitName==='НЕТ ДОКУМЕНТА'||permitType==='ОТСУТСТВУЕТ';const permit=$('.qc-document.permit');permit?.classList.toggle('qc-doc-missing',missing);set('permitNo',missing?'НЕ ВЫДАНО':serial(seed^0x1ac3,'E'));set('permitAuthority',missing?'—':'ENTRY AUTHORITY 07');set('destination',missing?'—':(dest[purpose]||'ТЕРМИНАЛ-07'));set('clearance',missing?'—':permitType);set('registry',missing?'НЕТ ЗАПИСИ':`REG-${two(val(seed,1,99,13))}/${String(2026).slice(2)}`);set('routeCheck',missing?'НЕ ПРОЙДЕН':route.includes('Веспер')?'РУЧНАЯ СВЕРКА':'AUTO-CLEAR');set('permitStatus',missing?'ОТСУТСТВУЕТ':'ACTIVE');set('permitNote',missing?'Разрешение на въезд в реестре не обнаружено.':'Документ действует только для указанной цели, маршрута и срока пребывания.');set('permitBarcode',missing?'NO-PERMIT':serial(seed^0x7812,'R'));
}
new MutationObserver(render).observe(nameEl,{childList:true,characterData:true,subtree:true});
['passportNo','passportNation','passportExpiry','testResult','testAge','temperature','permitName','permitType','purpose','route'].forEach(id=>{const el=$('#'+id);if(el)new MutationObserver(render).observe(el,{childList:true,characterData:true,subtree:true})});
ensureStructures();render();
})();