(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const NATIONS=['Арден','Норда','Веспер','Лира','Кармин','Остара'];
const FIRST=['Мира','Антон','Елена','Илья','София','Макс','Лев','Ника','Артур','Дана','Роман','Алиса','Марко','Лея','Тимур','Эмма'];
const LAST=['Вейл','Коста','Рейн','Орлов','Моретти','Кан','Северин','Лорен','Браун','Азар','Исаев','Харт','Волков','Мэй'];
const PURPOSES=['работа','транзит','семья','лечение','учёба','дипмиссия'];
const dayRules={
1:{title:'Базовый карантинный режим',seconds:150,queue:8,rules:['Имя во всех документах должно совпадать.','Паспорт не должен быть просрочен.','Медицинский тест должен быть отрицательным и не старше 72 часов.','Температура выше 37.4°C — отказ во въезде.']},
2:{title:'Кармин объявлен красной зоной',seconds:155,queue:9,rules:['Все правила предыдущего дня сохраняются.','Для прибывающих из Кармина тест должен быть не старше 24 часов.','Въезд из Кармина разрешён только при наличии разрешения на въезд.']},
3:{title:'Усиленный биоконтроль',seconds:160,queue:10,rules:['Все правила предыдущего дня сохраняются.','Пассажиры с маршрутом через Веспер обязаны иметь разрешение на въезд.','Результат «сомнительный» приравнивается к положительному.','Сотрудники медслужб могут иметь температуру до 37.7°C только при цели «лечение».']},
4:{title:'Штамм Q-17: режим максимальной готовности',seconds:165,queue:11,rules:['Все правила предыдущего дня сохраняются.','Любой тест старше 48 часов недействителен, кроме Кармина — там по-прежнему максимум 24 часа.','Любой выявленный симптом при доппроверке — отказ.','Транзит без разрешения запрещён для всех стран.']}
};
let S={day:1,time:150,running:false,queue:[],current:null,processed:0,correct:0,credits:0,reputation:100,strikes:0,leaks:0,risk:0,inspected:false,decisionLock:false,timer:null};
const pad=n=>String(n).padStart(2,'0'),pick=a=>a[Math.floor(Math.random()*a.length)],chance=p=>Math.random()<p;
function fmtClock(){const m=Math.floor(S.time/60),s=Math.max(0,S.time%60);$('#clock').textContent=pad(m)+':'+pad(s)}
function log(text,tone=''){const row=document.createElement('div');row.className='log-line '+tone;row.innerHTML=`<b>${tone==='bad'?'ОШИБКА':tone==='good'?'ВЕРНО':'СИСТЕМА'}</b> ${text}`;$('#log').prepend(row);while($('#log').children.length>7)$('#log').lastElementChild.remove()}
function rulesForDay(day=S.day){return dayRules[Math.min(day,4)]}
function passportNumber(){return pick(['AR','NV','VS','LR','KM','OS'])+'-'+Math.floor(100000+Math.random()*899999)}
function makePerson(i){
 const nation=pick(NATIONS),name=pick(FIRST)+' '+pick(LAST),purpose=pick(PURPOSES),route=chance(.24)?pick(NATIONS)+' → '+nation:nation+' → Терминал-07';
 let p={id:i,name,nation,purpose,route,passportNo:passportNumber(),passportExpiry:2027+Math.floor(Math.random()*3),test:'ОТРИЦАТЕЛЬНЫЙ',testAge:Math.floor(8+Math.random()*54),temp:+(36.2+Math.random()*1.15).toFixed(1),permit:chance(.82),permitType:purpose==='лечение'?'MED':purpose==='транзит'?'TRANSIT':'ENTRY',stay:(1+Math.floor(Math.random()*21))+' дн.',healthName:name,permitName:name,hidden:null,suspicious:false};
 const faults=[];const faultBudget=Math.random();
 if(faultBudget<.58){const count=chance(.22)?2:1;for(let k=0;k<count;k++){const options=['name','expiry','test','age','temp','permit','hidden'];let f=pick(options);if(faults.includes(f))continue;faults.push(f);if(f==='name'){if(chance(.5))p.healthName=name.replace(/.$/,'а');else p.permitName=name.split(' ').reverse().join(' ')}if(f==='expiry')p.passportExpiry=2025;if(f==='test')p.test=chance(.35)?'СОМНИТЕЛЬНЫЙ':'ПОЛОЖИТЕЛЬНЫЙ';if(f==='age')p.testAge=76+Math.floor(Math.random()*36);if(f==='temp')p.temp=+(37.6+Math.random()*.8).toFixed(1);if(f==='permit')p.permit=false;if(f==='hidden'){p.hidden=pick(['СКРЫТЫЙ КАШЕЛЬ','ПОДДЕЛЬНАЯ МЕДСПРАВКА','НЕСОВПАДЕНИЕ БИОМЕТРИИ']);p.suspicious=true}}}
 if(S.day>=2&&nation==='Кармин'&&chance(.42))p.testAge=30+Math.floor(Math.random()*40);
 if(S.day>=3&&route.includes('Веспер')&&chance(.4))p.permit=false;
 if(S.day>=4&&purpose==='транзит'&&chance(.35))p.permit=false;
 return p
}
function violations(p){const v=[];if(p.healthName!==p.name||p.permitName!==p.name)v.push('имена в документах не совпадают');if(p.passportExpiry<2026)v.push('паспорт просрочен');if(p.test!=='ОТРИЦАТЕЛЬНЫЙ')v.push('недействительный результат теста');const maxAge=p.nation==='Кармин'&&S.day>=2?24:S.day>=4?48:72;if(p.testAge>maxAge)v.push(`тест старше ${maxAge} часов`);const medException=S.day>=3&&p.purpose==='лечение';if(p.temp>(medException?37.7:37.4))v.push('повышенная температура');if(S.day>=2&&p.nation==='Кармин'&&!p.permit)v.push('нет обязательного разрешения');if(S.day>=3&&p.route.includes('Веспер')&&!p.permit)v.push('маршрут через Веспер без разрешения');if(S.day>=4&&p.purpose==='транзит'&&!p.permit)v.push('транзит без разрешения');if(p.hidden)v.push(p.hidden.toLowerCase());return v}
function dialogueFor(p){if(p.suspicious)return pick(['Я немного тороплюсь. Можно без лишних проверок?','Нет, я не кашлял. Вам показалось.','Документы настоящие. Наверное. То есть — конечно настоящие.']);if(p.purpose==='лечение')return 'Я направляюсь в медицинский сектор. У меня срочный допуск.';if(p.nation==='Кармин'&&S.day>=2)return 'Да, я знаю про новые правила для Кармина.';return pick(['Все документы здесь. Надеюсь, это быстро.','Я только на несколько дней.','Мне сказали, что сегодня очередь меньше.','Можно уже проходить?'])}
function resetStampFx(){const ink=$('#decisionInk'),stack=$('.qc-doc-stack');if(ink){ink.className='qc-decision-ink';ink.textContent='ДОПУЩЕНО'}if(stack)stack.classList.remove('impact');$$('.qc-stamp-control').forEach(b=>b.classList.remove('pressing'))}
function setDecisionControls(disabled){$('#approveBtn').disabled=disabled;$('#denyBtn').disabled=disabled;if(disabled)$('#inspectBtn').disabled=true;else if(!S.inspected)$('#inspectBtn').disabled=false}
function fillPerson(p){S.inspected=false;S.decisionLock=false;resetStampFx();setDecisionControls(false);$('#personName').textContent=p.name;$('#personLine').textContent=`${p.nation} • ${p.purpose} • ${p.route}`;$('#dialogue').textContent=dialogueFor(p);$('#passportCountry').textContent=p.nation.toUpperCase();$('#passportName').textContent=p.name;$('#passportNo').textContent=p.passportNo;$('#passportNation').textContent=p.nation;$('#passportExpiry').textContent='31.12.'+p.passportExpiry;$('#healthName').textContent=p.healthName;$('#testResult').textContent=p.test;$('#testAge').textContent=p.testAge+' ч.';$('#temperature').textContent=p.temp.toFixed(1)+' °C';$('#permitName').textContent=p.permit?p.permitName:'НЕТ ДОКУМЕНТА';$('#permitType').textContent=p.permit?p.permitType:'ОТСУТСТВУЕТ';$('#purpose').textContent=p.purpose;$('#stay').textContent=p.stay;$('#route').textContent=p.route;$('#avatarFace').textContent=pick(['•‿•','•︵•','•ᴗ•','•_•','•﹏•']);$('#docPhoto').textContent=pick(['◎','◉','◍','◌']);$('#queueCount').textContent=S.queue.length;$$('.qc-document').forEach((x,i)=>x.classList.toggle('active',i===0));$$('.qc-doc-tabs button').forEach((x,i)=>x.classList.toggle('active',i===0))}
function nextPerson(){if(!S.running)return;if(!S.queue.length){finishShift();return}S.current=S.queue.shift();fillPerson(S.current)}
function resolveDecision(approve){if(!S.current||!S.running)return;const v=violations(S.current),shouldApprove=v.length===0,ok=approve===shouldApprove;S.processed++;if(ok){S.correct++;S.credits+=12;S.reputation=Math.min(100,S.reputation+1);log(`${S.current.name}: решение принято верно.`,'good')}else{S.strikes++;S.credits=Math.max(0,S.credits-18);S.reputation=Math.max(0,S.reputation-11);let detail=v.length?v[0]:'оснований для отказа не было';log(`${S.current.name}: неверное решение — ${detail}.`,'bad');if(approve&&v.length){S.leaks++;S.risk=Math.min(100,S.risk+14+(S.current.hidden?10:0))}}
 updateStatus();S.current=null;if(S.strikes>=3){S.decisionLock=false;finishShift(true);return}setTimeout(nextPerson,300)}
function animateDecision(approve){if(!S.current||!S.running||S.decisionLock)return;S.decisionLock=true;setDecisionControls(true);const btn=$(approve?'#approveBtn':'#denyBtn'),ink=$('#decisionInk'),stack=$('.qc-doc-stack');btn.classList.remove('pressing');void btn.offsetWidth;btn.classList.add('pressing');ink.className='qc-decision-ink '+(approve?'approve':'deny');ink.textContent=approve?'ДОПУЩЕНО':'ОТКАЗАНО';stack.classList.remove('impact');void stack.offsetWidth;setTimeout(()=>{if(!S.running)return;stack.classList.add('impact');ink.classList.add('hit');if(navigator.vibrate)navigator.vibrate(18)},105);setTimeout(()=>resolveDecision(approve),510);setTimeout(()=>{btn.classList.remove('pressing');stack.classList.remove('impact')},690)}
function inspect(){if(!S.current||S.inspected||!S.running||S.decisionLock)return;S.inspected=true;S.time=Math.max(0,S.time-6);$('#inspectBtn').disabled=true;if(S.current.hidden){$('#dialogue').textContent='СКАНЕР: '+S.current.hidden+'. Допуск не рекомендован.';log(`${S.current.name}: доппроверка выявила «${S.current.hidden.toLowerCase()}».`,'bad')}else{$('#dialogue').textContent='СКАНЕР: скрытых нарушений не обнаружено.';log(`${S.current.name}: дополнительная проверка чистая.`,'good')}fmtClock()}
function updateStatus(){const risk=S.risk<20?'НИЗКИЙ':S.risk<45?'СРЕДНИЙ':S.risk<70?'ВЫСОКИЙ':'КРИТИЧЕСКИЙ';$('#reputation').textContent=S.reputation;$('#credits').textContent=S.credits+' ¤';$('#strikes').textContent=S.strikes+' / 3';$('#bioRisk').textContent=risk;$('#bioRisk').style.color=S.risk<20?'#91c79a':S.risk<45?'#d3a75b':'#d9685f'}
function renderRules(){const cfg=rulesForDay();$('#bulletinTitle').textContent=cfg.title;$('#dayLabel').textContent='День '+S.day;$('#ruleCount').textContent=cfg.rules.length;$('#rulesList').innerHTML=cfg.rules.slice(-4).map(x=>`<div class="rule-line">${x}</div>`).join('');$('#rulesFull').innerHTML=cfg.rules.map((x,i)=>`<div class="full-rule"><b>${pad(i+1)}</b> — ${x}</div>`).join('')}
function startShift(){const cfg=rulesForDay();S.time=cfg.seconds;S.queue=Array.from({length:cfg.queue},(_,i)=>makePerson(i));S.processed=0;S.correct=0;S.leaks=0;S.strikes=0;S.decisionLock=false;S.running=true;$('#startOverlay').classList.add('hidden');$('#shiftOverlay').classList.add('hidden');renderRules();updateStatus();fmtClock();clearInterval(S.timer);S.timer=setInterval(()=>{if(!S.running||document.hidden)return;S.time--;fmtClock();if(S.time<=0)finishShift()},1000);nextPerson()}
function finishShift(fired=false){if(!S.running)return;S.running=false;S.decisionLock=false;clearInterval(S.timer);setDecisionControls(true);const missed=S.queue.length+(S.current?1:0),accuracy=S.processed?Math.round(S.correct/S.processed*100):0;$('#sumProcessed').textContent=S.processed;$('#sumCorrect').textContent=S.correct;$('#sumLeaks').textContent=S.leaks;$('#sumCredits').textContent=S.credits+' ¤';let title='СМЕНА ЗАВЕРШЕНА',text=`Точность решений: ${accuracy}%. Не обработано: ${missed}.`;let headline=S.leaks===0?'Карантинный рубеж удержан. Новых цепочек заражения не зафиксировано.':S.leaks===1?'Через терминал прошёл один потенциально опасный пассажир. Санслужбы начинают отслеживание контактов.':`Санслужбы сообщают о ${S.leaks} возможных заносах. Терминал №07 оказался под проверкой.`;if(fired){title='ДОПУСК ОТОЗВАН';text='Три ошибки за одну смену. Руководство отстранило инспектора от работы.';headline='Комиссия начинает служебное расследование. Пост передан резервной смене.'}$('#shiftTitle').textContent=title;$('#shiftText').textContent=text;$('#headline').textContent=headline;$('#nextDayBtn').textContent=fired?'Начать кампанию заново':S.day>=4?'Новая кампания':'Следующая смена';$('#shiftOverlay').classList.remove('hidden')}
function nextDay(){if(S.strikes>=3||S.day>=4){S={day:1,time:150,running:false,queue:[],current:null,processed:0,correct:0,credits:0,reputation:100,strikes:0,leaks:0,risk:0,inspected:false,decisionLock:false,timer:null}}else S.day++;startShift()}
$$('.qc-doc-tabs button').forEach(b=>b.onclick=()=>{$$('.qc-doc-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.qc-document').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.doc))});
$('#approveBtn').onclick=()=>animateDecision(true);$('#denyBtn').onclick=()=>animateDecision(false);$('#inspectBtn').onclick=inspect;$('#startBtn').onclick=startShift;$('#nextDayBtn').onclick=nextDay;$('#rulesBtn').onclick=()=>{$('#rulesOverlay').classList.remove('hidden');renderRules()};$('#closeRules').onclick=()=>$('#rulesOverlay').classList.add('hidden');$('#rulesOverlay').onclick=e=>{if(e.target===$('#rulesOverlay'))$('#rulesOverlay').classList.add('hidden')};document.addEventListener('visibilitychange',()=>{});renderRules();updateStatus();fmtClock();
})();